# Generated by Django 6.1 on 2026-09-09 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagens_cadastros', '0003_remove_cargo_ativo_remove_combustivel_ativo_and_more'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNumeracaoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('numero_inicial', models.PositiveIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='ModeloJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('is_padrao', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='viagens_justif_nome_unico'), models.UniqueConstraint(condition=models.Q(('is_padrao', True)), fields=('is_padrao',), name='viagens_justif_padrao_unico')],
            },
        ),
        migrations.CreateModel(
            name='ModeloMotivoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('is_padrao', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='viagens_motivo_nome_unico'), models.UniqueConstraint(condition=models.Q(('is_padrao', True)), fields=('is_padrao',), name='viagens_motivo_padrao_unico')],
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cancelado', models.BooleanField(default=False, verbose_name='cancelado')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data_criacao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('protocolo', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('assunto', models.CharField(blank=True, default='', max_length=255)),
                ('motivo', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado'), ('FINALIZADO', 'Finalizado (legado)'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20)),
                ('custeio', models.CharField(choices=[('UNIDADE_DPC', 'Unidade DPC'), ('OUTRA_INSTITUICAO', 'Outra instituição'), ('ONUS_LIMITADO', 'Ônus limitado')], default='UNIDADE_DPC', max_length=30)),
                ('custeio_observacao', models.CharField(blank=True, default='', max_length=255)),
                ('diarias_quantidade_servidores', models.PositiveIntegerField(blank=True, editable=False, help_text='Snapshot do efetivo usado no total de diárias; não muda quando um servidor é excluído posteriormente do cadastro.', null=True, verbose_name='Quantidade de servidores considerada nas diárias')),
                ('porte_transporte_armas', models.BooleanField(default=True, verbose_name='Porte/transporte de armas')),
                ('transporte_placa_manual', models.CharField(blank=True, default='', max_length=7)),
                ('transporte_modelo_manual', models.CharField(blank=True, default='', max_length=120)),
                ('transporte_tipo_manual', models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='', max_length=20)),
                ('motorista_modo', models.CharField(choices=[('SERVIDOR', 'Servidor'), ('MANUAL', 'Manual')], default='SERVIDOR', max_length=10)),
                ('motorista_manual_nome', models.CharField(blank=True, default='', max_length=255)),
                ('motorista_manual_rg', models.CharField(blank=True, default='', max_length=30)),
                ('motorista_manual_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('motorista_manual_cargo', models.CharField(blank=True, default='', max_length=120)),
                ('motorista_manual_unidade', models.CharField(blank=True, default='', max_length=255)),
                ('motorista_manual_observacao', models.TextField(blank=True, default='')),
                ('motorista_oficio_referencia', models.CharField(blank=True, default='', help_text='Referência no formato número/ano (ex.: 15/2026).', max_length=16, verbose_name='Ofício do motorista')),
                ('motorista_protocolo_ref', models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo do motorista')),
                ('retificado_documento', models.BooleanField(default=False, help_text='Quando verdadeiro e o ofício seria Autorização por datas, o documento usa o rótulo Retificado.', verbose_name='Emitir como retificado')),
                ('complementar_documento', models.BooleanField(default=False, help_text='Quando verdadeiro, o documento usa o rótulo Complementar ao lado do número do ofício.', verbose_name='Emitir como complementar')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_motorista', to='viagens_cadastros.servidor')),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='viagens_roteiros.roteiro')),
                ('servidores', models.ManyToManyField(blank=True, related_name='oficios', to='viagens_cadastros.servidor')),
                ('servidores_termo_autorizacao', models.ManyToManyField(blank=True, related_name='oficios_termo_autorizacao', to='viagens_cadastros.servidor', verbose_name='Servidores com Termo de Autorização')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.unidade')),
                ('transporte_combustivel_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.combustivel')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='viagens_cadastros.viatura')),
            ],
            options={
                'ordering': ['-data_criacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('texto', models.TextField(blank=True, default='')),
                ('obrigatoria', models.BooleanField(default=False)),
                ('dias_antecedencia', models.IntegerField(blank=True, null=True)),
                ('prazo_dias', models.PositiveIntegerField(default=10)),
                ('primeira_saida_dt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADA', 'Finalizada')], default='RASCUNHO', max_length=20)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='viagens_oficios.modelojustificativa')),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa', to='viagens_oficios.oficio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OficioNumeroLacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(db_index=True)),
                ('numero', models.PositiveIntegerField()),
                ('liberado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ano', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'numero'), name='viagens_oficio_lacuna_unica')],
            },
        ),
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('ano', 'numero'), name='viagens_oficio_ano_numero_unique'),
        ),
    ]
