# Generated by Django 5.2.16 on 2026-09-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_oficios', '0002_origem_legado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelojustificativa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='modelomotivooficio',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='modelojustificativa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='modelojustificativa',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='modelomotivooficio',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='modelomotivooficio',
            name='ordem',
        ),
    ]
