# Generated by Django 5.2.16 on 2026-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_oficios', '0003_modelos_sem_ativo_nem_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('GERADO', 'Gerado'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20),
        ),
    ]
