# Generated by Django 6.1.1 on 2026-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_oficios", "0005_oficio_viagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficio",
            name="protocolo_criado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="oficio",
            name="protocolo_origem",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Informado manualmente"),
                    ("EPROTOCOLO", "Aberto no eProtocolo"),
                    (
                        "TREINAMENTO",
                        "Aberto no eProtocolo de treinamento (não oficial)",
                    ),
                    ("SIMULADO", "Simulado (integração desligada)"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="origem do protocolo",
            ),
        ),
        migrations.AddField(
            model_name="oficio",
            name="protocolo_situacao",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
