# Generated by Django 6.1 on 2026-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_estado_municipio_estado_codigo_ibge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'unidade móvel',
                'verbose_name_plural': 'unidades móveis',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
