# Generated by Django 6.1 on 2026-09-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude'),
        ),
    ]
