# Generated by Django 6.1.1 on 2026-09-26 04:20

from django.db import migrations, models

# Pontos de partida; a DG edita, inativa ou acrescenta em Cadastros.
TEXTOS_INICIAIS = [
    ("Falta o ofício", "Falta o ofício do solicitante. Anexe o ofício e reenvie."),
    ("Data em conflito", "A data conflita com outro evento já deferido. Avalie outra data."),
    ("Sem equipe disponível", "Não há equipe disponível para a data informada."),
    ("Complete as equipes", "Informe as equipes e a quantidade de servidores de cada uma."),
]


def criar_textos(apps, schema_editor):
    TextoDespacho = apps.get_model("cadastros", "TextoDespacho")
    for nome, texto in TEXTOS_INICIAIS:
        TextoDespacho.objects.get_or_create(nome=nome, defaults={"texto": texto})


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_tipos_de_evento_enxutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextoDespacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, unique=True, verbose_name="nome"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("texto", models.TextField(verbose_name="texto")),
            ],
            options={
                "verbose_name": "texto pronto do despacho",
                "verbose_name_plural": "textos prontos do despacho",
                "ordering": ["nome"],
                "abstract": False,
            },
        ),
        migrations.RunPython(criar_textos, migrations.RunPython.noop),
    ]
