# Generated by Django 6.1.1 on 2026-09-26 04:29

import django.db.models.deletion
from django.db import migrations, models


def parana_em_acao_vira_modelo(apps, schema_editor):
    """A regra fixa do "Paraná em Ação" (solicitante e cargo gravados à força)
    passa a ser o modelo do tipo: sugerido na tela, aplicado com um clique."""
    TipoEvento = apps.get_model("cadastros", "TipoEvento")
    for tipo in TipoEvento.objects.all():
        if tipo.nome.strip().casefold() == "paraná em ação":
            tipo.solicitante_padrao = tipo.solicitante_padrao or "Paraná em Ação"
            tipo.cargo_padrao = tipo.cargo_padrao or "SEJU"
            tipo.save(update_fields=["solicitante_padrao", "cargo_padrao"])


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_textos_despacho"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoevento",
            name="cargo_padrao",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="cargo / unidade padrão"
            ),
        ),
        migrations.AddField(
            model_name="tipoevento",
            name="orgao_padrao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tipos_evento_padrao",
                to="cadastros.orgaoresponsavel",
                verbose_name="órgão responsável padrão",
            ),
        ),
        migrations.AddField(
            model_name="tipoevento",
            name="servicos_sugeridos",
            field=models.ManyToManyField(
                blank=True,
                related_name="tipos_evento_sugeridos",
                to="cadastros.servico",
                verbose_name="serviços sugeridos",
            ),
        ),
        migrations.AddField(
            model_name="tipoevento",
            name="solicitante_padrao",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="solicitante padrão"
            ),
        ),
        migrations.CreateModel(
            name="TipoEventoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="quantidade de servidores"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_evento_sugeridos",
                        to="cadastros.equipe",
                        verbose_name="equipe",
                    ),
                ),
                (
                    "tipo_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes_sugeridas",
                        to="cadastros.tipoevento",
                        verbose_name="tipo de evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipe sugerida do tipo de evento",
                "verbose_name_plural": "equipes sugeridas do tipo de evento",
                "ordering": ["equipe__nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo_evento", "equipe"),
                        name="equipe_sugerida_unica_por_tipo",
                    )
                ],
            },
        ),
        migrations.RunPython(parana_em_acao_vira_modelo, migrations.RunPython.noop),
    ]
