# Generated by Django 5.2.16 on 2026-08-31 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_setor_modulo_user_setores'),
        ('cadastros', '0007_normaliza_nomes_em_caixa_alta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, unique=True, verbose_name='tipo')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'resposta padrão',
                'verbose_name_plural': 'respostas padrão',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('municipio_texto', models.CharField(blank=True, max_length=150, verbose_name='município (texto original)')),
                ('divisao', models.CharField(blank=True, max_length=100, verbose_name='divisão')),
                ('lotacao', models.CharField(blank=True, max_length=150, verbose_name='lotação')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='palestrantes_ascom', to='cadastros.municipio', verbose_name='município')),
                ('temas', models.ManyToManyField(blank=True, related_name='palestrantes', to='demandas_eventos.tema', verbose_name='temas')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DemandaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_RETORNO', 'Aguardando retorno'), ('EM_ANDAMENTO', 'Em andamento'), ('EVENTO_AGENDADO', 'Evento agendado'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDER', 'Não atender'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=25, verbose_name='status')),
                ('data_solicitacao', models.DateField(verbose_name='data da solicitação')),
                ('canal_solicitacao', models.CharField(blank=True, max_length=150, verbose_name='solicitado via')),
                ('municipio_texto', models.CharField(blank=True, max_length=150, verbose_name='município (texto original)')),
                ('data_inicio_evento', models.DateField(blank=True, null=True, verbose_name='início do evento')),
                ('data_fim_evento', models.DateField(blank=True, null=True, verbose_name='fim do evento')),
                ('periodo_evento_texto', models.CharField(blank=True, max_length=200, verbose_name='período do evento')),
                ('solicitante', models.CharField(max_length=300, verbose_name='solicitante')),
                ('contato', models.CharField(blank=True, max_length=300, verbose_name='contato')),
                ('assunto_email', models.CharField(blank=True, max_length=300, verbose_name='assunto do e-mail')),
                ('pedido_contato', models.TextField(blank=True, verbose_name='pedido / contato')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('informacoes_previas', models.TextField(blank=True, verbose_name='informações prévias')),
                ('responsavel_organizacao', models.CharField(blank=True, max_length=200, verbose_name='responsável pela organização')),
                ('responsavel_atendimento_texto', models.CharField(blank=True, max_length=200, verbose_name='responsável pelo atendimento (texto original)')),
                ('servidor_texto', models.CharField(blank=True, max_length=300, verbose_name='servidor (texto original)')),
                ('unidade', models.CharField(blank=True, max_length=200, verbose_name='unidade')),
                ('quantidade_publico', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de público')),
                ('briefing', models.TextField(blank=True, verbose_name='briefing')),
                ('materia_site', models.TextField(blank=True, verbose_name='matéria no site')),
                ('origem_importacao', models.CharField(blank=True, max_length=100, verbose_name='origem da importação')),
                ('chave_importacao', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='chave da importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas_ascom_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas_ascom', to='cadastros.municipio', verbose_name='município')),
                ('responsavel_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_ascom_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='responsável pelo atendimento')),
                ('setores', models.ManyToManyField(related_name='demandas_eventos', to='accounts.setor', verbose_name='setores envolvidos')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas_ascom', to='cadastros.tipoevento', verbose_name='tipo de evento')),
                ('palestrantes', models.ManyToManyField(blank=True, related_name='demandas', to='demandas_eventos.palestrante', verbose_name='palestrantes')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='demandas_eventos.tema', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'demanda de evento',
                'verbose_name_plural': 'demandas de eventos',
                'ordering': ['-data_solicitacao', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='palestrante',
            constraint=models.UniqueConstraint(fields=('nome', 'lotacao'), name='palestrante_unico_por_nome_lotacao'),
        ),
        migrations.AddIndex(
            model_name='demandaevento',
            index=models.Index(fields=['status', 'data_solicitacao'], name='demanda_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='demandaevento',
            index=models.Index(fields=['data_inicio_evento'], name='demanda_evento_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandaevento',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_evento__isnull', True), ('data_fim_evento__isnull', True), ('data_fim_evento__gte', models.F('data_inicio_evento')), _connector='OR'), name='demanda_periodo_evento_valido'),
        ),
    ]
