# Generated by Django 6.1 on 2026-09-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas_eventos', '0003_altera_tamanho_solicitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Demanda criada'), ('ATUALIZACAO', 'Demanda atualizada'), ('TRANSICAO', 'Status alterado')], max_length=20, verbose_name='ação')),
                ('status_anterior', models.CharField(blank=True, max_length=25, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, max_length=25, verbose_name='status novo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='demandas_eventos.demandaevento', verbose_name='demanda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_demandas_ascom', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'histórico de demanda ASCOM',
                'verbose_name_plural': 'históricos de demandas ASCOM',
                'ordering': ['criado_em', 'pk'],
            },
        ),
    ]
