# Generated by Django 5.2.16 on 2026-09-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas_eventos", "0004_workflow_historico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200, verbose_name="subtema")),
                ("escopo", models.TextField(blank=True, help_text="Explique o recorte que este subtema cobre.", verbose_name="escopo da abordagem")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("tema", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subtemas", to="demandas_eventos.tema", verbose_name="tema principal")),
            ],
            options={
                "verbose_name": "subtema e escopo",
                "verbose_name_plural": "subtemas e escopos",
                "ordering": ["tema__nome", "nome"],
            },
        ),
        migrations.AddField(
            model_name="demandaevento",
            name="subtema",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="demandas", to="demandas_eventos.subtema", verbose_name="subtema"),
        ),
        migrations.AddConstraint(
            model_name="subtema",
            constraint=models.UniqueConstraint(fields=("tema", "nome"), name="subtema_unico_por_tema"),
        ),
    ]
