# Generated by Django 5.2.16 on 2026-09-21 18:48

from django.db import migrations, models


def texto_para_horarios(apps, schema_editor):
    """O horário que estava escrito vira início e fim; o resto fica como observação."""
    from demandas_eventos.horarios import extrair_horarios

    DemandaEvento = apps.get_model("demandas_eventos", "DemandaEvento")
    for demanda in DemandaEvento.objects.exclude(periodo_evento_texto=""):
        inicio, fim, sobra = extrair_horarios(demanda.periodo_evento_texto)
        if inicio or fim:
            demanda.hora_inicio, demanda.hora_fim = inicio, fim
            demanda.periodo_evento_texto = sobra
            demanda.save(update_fields=["hora_inicio", "hora_fim", "periodo_evento_texto"])


class Migration(migrations.Migration):

    dependencies = [
        ('demandas_eventos', '0008_so_temas_da_planilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandaevento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de término'),
        ),
        migrations.AddField(
            model_name='demandaevento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de início'),
        ),
        migrations.AlterField(
            model_name='demandaevento',
            name='periodo_evento_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='observação do período'),
        ),
        migrations.RunPython(texto_para_horarios, migrations.RunPython.noop),
    ]
