# Generated by Django 5.2.16 on 2026-09-21 19:01

from django.db import migrations, models


def separar_contato(apps, schema_editor):
    """O "Contato" da planilha vira telefone e e-mail; o que sobra fica como texto."""
    from demandas_eventos.planilha import telefone_e_email

    DemandaEvento = apps.get_model("demandas_eventos", "DemandaEvento")
    for demanda in DemandaEvento.objects.exclude(contato=""):
        telefone, email, sobra = telefone_e_email(demanda.contato)
        demanda.telefone, demanda.email, demanda.contato = telefone, email, sobra
        demanda.save(update_fields=["telefone", "email", "contato"])


class Migration(migrations.Migration):

    dependencies = [
        ('demandas_eventos', '0010_temas_palestrantes_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandaevento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='demandaevento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='demandaevento',
            name='contato',
            field=models.CharField(blank=True, max_length=300, verbose_name='contato (texto da planilha)'),
        ),
        migrations.RunPython(separar_contato, migrations.RunPython.noop),
    ]
