# Generated by Django 5.2.16 on 2026-09-21 19:28

from django.db import migrations, models


def termino_para_texto(apps, schema_editor):
    """Um horário só na tela: o término que existia fica escrito na observação."""
    DemandaEvento = apps.get_model("demandas_eventos", "DemandaEvento")
    for demanda in DemandaEvento.objects.filter(hora_fim__isnull=False):
        texto = " ".join(x for x in (f"até {demanda.hora_fim:%H:%M}", demanda.periodo_evento_texto) if x)
        demanda.periodo_evento_texto = texto[:200]
        demanda.save(update_fields=["periodo_evento_texto"])


class Migration(migrations.Migration):

    dependencies = [
        ('demandas_eventos', '0011_telefone_e_email'),
    ]

    operations = [
        migrations.RunPython(termino_para_texto, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='demandaevento',
            name='hora_fim',
        ),
        migrations.AlterField(
            model_name='demandaevento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='horário'),
        ),
    ]
