# Generated by Django 6.1.1 on 2026-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas_eventos", "0012_um_horario_so"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicodemanda",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Registro criado"),
                    ("ATUALIZACAO", "Registro atualizado"),
                    ("TRANSICAO", "Status alterado"),
                    ("RESPOSTA", "Resposta enviada"),
                ],
                max_length=20,
                verbose_name="ação",
            ),
        ),
    ]
