# Generated by Django 6.1.1 on 2026-09-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas_eventos", "0013_resposta_padrao_no_historico"),
        ("solicitacoes", "0020_historico_alteracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandaevento",
            name="solicitacao_dg",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demanda_ascom",
                to="solicitacoes.solicitacaoevento",
                verbose_name="solicitação de evento (DG)",
            ),
        ),
        migrations.AlterField(
            model_name="historicodemanda",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Registro criado"),
                    ("ATUALIZACAO", "Registro atualizado"),
                    ("TRANSICAO", "Status alterado"),
                    ("RESPOSTA", "Resposta enviada"),
                    ("ENCAMINHAMENTO_DG", "Encaminhada à DG"),
                    ("ANDAMENTO_DG", "Andamento na DG"),
                ],
                max_length=20,
                verbose_name="ação",
            ),
        ),
    ]
