# Generated by Django 6.1.1 on 2026-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas_eventos", "0014_encaminhar_a_dg"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandaevento",
            name="anexo_pedido",
            field=models.FileField(
                blank=True,
                upload_to="demandas_eventos/pedidos/%Y/",
                verbose_name="anexo do pedido",
            ),
        ),
        migrations.AddField(
            model_name="demandaevento",
            name="token_acompanhamento",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=64,
                verbose_name="token de acompanhamento (hash)",
            ),
        ),
        migrations.AlterField(
            model_name="demandaevento",
            name="canal_solicitacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "E-mail"),
                    ("WHATSAPP", "WhatsApp"),
                    ("PROTOCOLO", "Protocolo"),
                    ("TELEFONE", "Telefone"),
                    ("PRESENCIAL", "Presencial"),
                    ("PORTAL", "Formulário público"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
                verbose_name="foi solicitado via",
            ),
        ),
    ]
