# Generated by Django 6.1.1 on 2026-09-26 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demandas_eventos", "0015_pedido_publico"),
        (
            "viagens_cadastros",
            "0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="palestrante",
            name="servidor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="palestrantes_ascom",
                to="viagens_cadastros.servidor",
                verbose_name="servidor no cadastro de Viagens",
            ),
        ),
    ]
