# Generated by Django 6.1 on 2026-08-31 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIACAO", "Criação"),
                            ("ATUALIZACAO", "Atualização"),
                            ("EXCLUSAO", "Exclusão"),
                        ],
                        max_length=12,
                        verbose_name="ação",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="modelo"
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="id do objeto"
                    ),
                ),
                (
                    "objeto_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="representação"
                    ),
                ),
                (
                    "alteracoes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="alterações"
                    ),
                ),
                (
                    "caminho_requisicao",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="caminho da requisição"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criado em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "registros de auditoria",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["modelo", "objeto_id", "-criado_em"],
                        name="auditoria_objeto_idx",
                    )
                ],
            },
        ),
    ]
