# Generated by Django 5.2.16 on 2026-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='origem',
            field=models.CharField(choices=[('formulario', 'Formulário'), ('editor', 'Editor documental'), ('sistema', 'Sistema')], default='sistema', max_length=12, verbose_name='origem'),
        ),
    ]
