# Generated by Django 6.1 on 2026-09-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0008_remove_motorista"),
        ("solicitacoes", "0019_motorista_aponta_para_servidor"),
        ("viagens_cadastros", "0002_seed_modulo_viagens"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cancelado",
                    models.BooleanField(default=False, verbose_name="cancelado"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "cancelado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelado em"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AVULSO", "Avulso"),
                            ("EVENTO", "De solicitação de evento"),
                        ],
                        default="AVULSO",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "saida_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="saída da sede"
                    ),
                ),
                (
                    "chegada_dt",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="chegada ao primeiro destino",
                    ),
                ),
                (
                    "retorno_saida_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="saída para o retorno"
                    ),
                ),
                (
                    "retorno_chegada_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="chegada de volta à sede"
                    ),
                ),
                (
                    "quantidade_servidores",
                    models.PositiveIntegerField(default=1, verbose_name="servidores"),
                ),
                (
                    "resumo_diarias",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="composição das diárias",
                    ),
                ),
                (
                    "valor_diarias",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor das diárias",
                    ),
                ),
                (
                    "valor_diarias_extenso",
                    models.TextField(blank=True, verbose_name="valor por extenso"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "origem_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roteiros_como_sede",
                        to="cadastros.municipio",
                        verbose_name="município sede",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiros",
                        to="solicitacoes.solicitacaoevento",
                        verbose_name="solicitação de evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "roteiro",
                "verbose_name_plural": "roteiros",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RoteiroDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("ordem", models.PositiveIntegerField(default=1, verbose_name="ordem")),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roteiro_destinos",
                        to="cadastros.municipio",
                        verbose_name="município",
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos",
                        to="viagens_roteiros.roteiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "destino do roteiro",
                "verbose_name_plural": "destinos do roteiro",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RoteiroDiariaComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("ordem", models.PositiveIntegerField(default=1, verbose_name="ordem")),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("CALCULO", "Calculada"),
                            ("LEGADO", "Importada do legado"),
                        ],
                        default="CALCULO",
                        max_length=12,
                        verbose_name="origem",
                    ),
                ),
                ("faixa", models.CharField(max_length=20, verbose_name="faixa")),
                (
                    "percentual",
                    models.PositiveSmallIntegerField(
                        choices=[(15, "15%"), (30, "30%"), (100, "100%")],
                        verbose_name="percentual",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="quantidade"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor unitário"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="subtotal"
                    ),
                ),
                (
                    "tabela_vigencia_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência a partir de"
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="início do período"
                    ),
                ),
                (
                    "periodo_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fim do período"
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes_diarias",
                        to="viagens_roteiros.roteiro",
                    ),
                ),
                (
                    "tabela_diaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="viagens_cadastros.tabeladiaria",
                        verbose_name="vigência aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela de diária",
                "verbose_name_plural": "parcelas de diária",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.CreateModel(
            name="RoteiroTrecho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("ordem", models.PositiveIntegerField(default=1, verbose_name="ordem")),
                (
                    "sentido",
                    models.CharField(
                        choices=[("IDA", "Ida"), ("RETORNO", "Retorno")],
                        default="IDA",
                        max_length=10,
                        verbose_name="sentido",
                    ),
                ),
                (
                    "saida_dt",
                    models.DateTimeField(blank=True, null=True, verbose_name="saída"),
                ),
                (
                    "chegada_dt",
                    models.DateTimeField(blank=True, null=True, verbose_name="chegada"),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="distância (km)",
                    ),
                ),
                (
                    "duracao_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duração (min)"
                    ),
                ),
                (
                    "destino_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trechos_como_destino",
                        to="cadastros.municipio",
                        verbose_name="destino",
                    ),
                ),
                (
                    "origem_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trechos_como_origem",
                        to="cadastros.municipio",
                        verbose_name="origem",
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trechos",
                        to="viagens_roteiros.roteiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "trecho do roteiro",
                "verbose_name_plural": "trechos do roteiro",
                "ordering": ["ordem", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="roteiro",
            index=models.Index(
                fields=["status", "-criado_em"], name="roteiro_status_criado_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("chegada_dt__gte", models.F("saida_dt"))),
                name="roteiro_saida_antes_da_chegada",
                violation_error_message="A chegada ao destino não pode ser anterior à saída da sede.",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("retorno_saida_dt__gte", models.F("chegada_dt"))),
                name="roteiro_chegada_antes_do_retorno",
                violation_error_message="A saída de retorno não pode ser anterior à chegada ao destino.",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retorno_chegada_dt__gte", models.F("retorno_saida_dt"))
                ),
                name="roteiro_retorno_ordenado",
                violation_error_message="A chegada de volta não pode ser anterior à saída de retorno.",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("retorno_chegada_dt__gte", models.F("saida_dt"))),
                name="roteiro_periodo_total_ordenado",
                violation_error_message="A volta à sede não pode ser anterior à saída.",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_diarias__gte", 0)),
                name="roteiro_valor_diarias_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodestino",
            constraint=models.UniqueConstraint(
                fields=("roteiro", "ordem"), name="roteiro_destino_ordem_unica"
            ),
        ),
        migrations.AddIndex(
            model_name="roteirodiariacomponente",
            index=models.Index(
                fields=["percentual", "periodo_inicio"],
                name="roteiro_parcela_busca_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodiariacomponente",
            constraint=models.UniqueConstraint(
                fields=("roteiro", "ordem"), name="roteiro_parcela_ordem_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodiariacomponente",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gt", 0)),
                name="roteiro_parcela_quantidade_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodiariacomponente",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_unitario__gte", 0)),
                name="roteiro_parcela_valor_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodiariacomponente",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="roteiro_parcela_subtotal_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirodiariacomponente",
            constraint=models.CheckConstraint(
                condition=models.Q(("periodo_fim__gte", models.F("periodo_inicio"))),
                name="roteiro_parcela_periodo_ordenado",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirotrecho",
            constraint=models.UniqueConstraint(
                fields=("roteiro", "ordem"), name="roteiro_trecho_ordem_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirotrecho",
            constraint=models.CheckConstraint(
                condition=models.Q(("chegada_dt__gte", models.F("saida_dt"))),
                name="roteiro_trecho_periodo_ordenado",
                violation_error_message="A chegada do trecho não pode ser anterior à saída.",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteirotrecho",
            constraint=models.CheckConstraint(
                condition=models.Q(("distancia_km__gte", 0)),
                name="roteiro_trecho_distancia_nao_negativa",
            ),
        ),
    ]
