# Generated by Django 6.1 on 2026-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_municipio_coordenadas'),
        ('solicitacoes', '0019_motorista_aponta_para_servidor'),
        ('viagens_roteiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='rota_assinatura',
            field=models.CharField(blank=True, max_length=128, verbose_name='assinatura do percurso'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rota calculada em'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distância da rota (km)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duração da rota (min)'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_fonte',
            field=models.CharField(blank=True, max_length=40, verbose_name='fonte da rota'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='geometria da rota'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='rota_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CALCULADA', 'Calculada'), ('DESATUALIZADA', 'Desatualizada')], default='PENDENTE', max_length=20, verbose_name='situação da rota'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, max_length=40, verbose_name='fonte da estimativa'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='tempo_adicional_min',
            field=models.PositiveIntegerField(default=0, verbose_name='tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='tempo_viagem_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo de viagem (min)'),
        ),
        migrations.AddConstraint(
            model_name='roteiro',
            constraint=models.CheckConstraint(condition=models.Q(('rota_distancia_km__gte', 0)), name='roteiro_rota_distancia_nao_negativa'),
        ),
    ]
