# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('solicitacoes', '0019_motorista_aponta_para_servidor'),
        ('viagens_cadastros', '0005_origem_legado'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='roteirodiariacomponente',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='roteirodiariacomponente',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='roteirotrecho',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='roteiro',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_roteiro_origem'),
        ),
        migrations.AddConstraint(
            model_name='roteirodestino',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_roteirodestino_origem'),
        ),
        migrations.AddConstraint(
            model_name='roteirodiariacomponente',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_roteirodiariacomponente_origem'),
        ),
        migrations.AddConstraint(
            model_name='roteirotrecho',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_roteirotrecho_origem'),
        ),
    ]
