# Generated by Django 6.1 on 2026-09-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_roteiros', '0003_origem_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteirotrecho',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rota calculada em'),
        ),
        migrations.AlterField(
            model_name='roteirodiariacomponente',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='roteirodiariacomponente',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor unitário'),
        ),
    ]
