# Generated by Django 6.1.1 on 2026-09-26 05:23

import django.db.models.deletion
from django.db import migrations, models


def guardar_distancias_dos_roteiros(apps, schema_editor):
    """Os trechos já calculados viram a primeira carga da tabela (m078)."""
    RoteiroTrecho = apps.get_model("viagens_roteiros", "RoteiroTrecho")
    DistanciaMunicipios = apps.get_model("viagens_roteiros", "DistanciaMunicipios")
    vistos = set()
    novos = []
    trechos = (
        RoteiroTrecho.objects.filter(
            origem_municipio__isnull=False, destino_municipio__isnull=False, distancia_km__gt=0
        )
        .order_by("-atualizado_em")
        .values_list("origem_municipio_id", "destino_municipio_id", "distancia_km", "duracao_min", "tempo_viagem_min")
    )
    for origem_id, destino_id, distancia, duracao, viagem in trechos:
        if origem_id == destino_id or (origem_id, destino_id) in vistos or (destino_id, origem_id) in vistos:
            continue
        vistos.add((origem_id, destino_id))
        novos.append(
            DistanciaMunicipios(
                origem_id=origem_id, destino_id=destino_id, distancia_km=distancia,
                duracao_min=duracao, tempo_viagem_min=viagem, fonte="roteiro",
            )
        )
    DistanciaMunicipios.objects.bulk_create(novos, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_modelo_por_tipo_de_evento"),
        ("viagens_roteiros", "0006_periodo_a_partir_dos_trechos"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanciaMunicipios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="distância (km)"
                    ),
                ),
                (
                    "duracao_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duração do serviço (min)"
                    ),
                ),
                (
                    "tempo_viagem_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tempo de viagem (min)"
                    ),
                ),
                (
                    "fonte",
                    models.CharField(
                        choices=[
                            ("openrouteservice", "Serviço de rotas"),
                            ("roteiro", "Trecho de roteiro"),
                            ("manual", "Corrigida manualmente"),
                        ],
                        default="openrouteservice",
                        max_length=20,
                        verbose_name="fonte",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cadastros.municipio",
                        verbose_name="destino",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cadastros.municipio",
                        verbose_name="origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "distância entre municípios",
                "verbose_name_plural": "distâncias entre municípios",
                "ordering": ["origem__nome", "destino__nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origem", "destino"),
                        name="distancia_municipios_par_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("distancia_km__gte", 0)),
                        name="distancia_municipios_km_nao_negativa",
                    ),
                ],
            },
        ),
        migrations.RunPython(guardar_distancias_dos_roteiros, migrations.RunPython.noop),
    ]
