# Generated by Django 6.1.1 on 2026-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_modelo_por_tipo_de_evento"),
        ("viagens_roteiros", "0007_distancia_municipios"),
    ]

    operations = [
        migrations.AddField(
            model_name="distanciamunicipios",
            name="legado_origem",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="origem no legado"
            ),
        ),
        migrations.AddField(
            model_name="distanciamunicipios",
            name="legado_pk",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="id no legado"
            ),
        ),
        migrations.AddConstraint(
            model_name="distanciamunicipios",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado_pk__isnull", False)),
                fields=("legado_origem", "legado_pk"),
                name="f6_distanciamunicipios_origem",
            ),
        ),
    ]
