# Generated by Django 6.1 on 2026-08-30 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('mensagem', models.CharField(blank=True, max_length=255, verbose_name='mensagem')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['usuario', 'lida'], name='core_notifi_usuario_cd404b_idx')],
            },
        ),
    ]
