# Generated by Django 6.1.1 on 2026-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notificacao_vinculada_a_solicitacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="data")),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "anual",
                    models.BooleanField(default=True, verbose_name="repete todo ano"),
                ),
            ],
            options={
                "verbose_name": "feriado",
                "verbose_name_plural": "feriados",
                "ordering": ["data"],
            },
        ),
    ]
