# Generated by Django 6.1.1 on 2026-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feriado"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoriaLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("remetente", "Remetente"),
                            ("dominio", "Domínio do remetente"),
                            ("palavra", "Palavra do assunto"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("chave", models.CharField(max_length=200, verbose_name="chave")),
                ("modulo", models.CharField(max_length=40, verbose_name="módulo")),
                (
                    "campo",
                    models.CharField(blank=True, max_length=60, verbose_name="campo"),
                ),
                (
                    "valor",
                    models.CharField(blank=True, max_length=500, verbose_name="valor"),
                ),
                (
                    "exibir",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="como mostrar"
                    ),
                ),
                ("vezes", models.PositiveIntegerField(default=1, verbose_name="vezes")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "memória de leitura",
                "verbose_name_plural": "memórias de leitura",
                "indexes": [
                    models.Index(
                        fields=["tipo", "chave"], name="core_memori_tipo_4f553d_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "chave", "modulo", "campo", "valor"),
                        name="core_memoria_leitura_unica",
                    )
                ],
            },
        ),
    ]
