# Generated by Django 6.1.1 on 2026-09-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_modelo_por_tipo_de_evento"),
        ("core", "0004_memoria_leitura"),
    ]

    operations = [
        migrations.AddField(
            model_name="feriado",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                help_text="Em branco: feriado geral (estadual ou ponto facultativo da casa).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feriados",
                to="cadastros.municipio",
                verbose_name="município (feriado municipal)",
            ),
        ),
    ]
