# Generated by Django 6.1 on 2026-08-29 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DESPACHO', 'Aguardando despacho'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=25, verbose_name='status')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da solicitação')),
                ('data_inicio_evento', models.DateField(verbose_name='data de início do evento')),
                ('data_fim_evento', models.DateField(verbose_name='data de fim do evento')),
                ('solicitante_nome', models.CharField(max_length=150, verbose_name='nome do solicitante')),
                ('solicitante_cargo', models.CharField(blank=True, max_length=100, verbose_name='cargo do solicitante')),
                ('solicitante_unidade', models.CharField(blank=True, max_length=150, verbose_name='unidade do solicitante')),
                ('contato', models.CharField(max_length=100, verbose_name='contato')),
                ('unidade_movel', models.BooleanField(default=False, verbose_name='unidade móvel')),
                ('veiculo_exposicao', models.BooleanField(default=False, verbose_name='veículo de exposição')),
                ('local_evento', models.CharField(max_length=255, verbose_name='local do evento')),
                ('descricao_complementar', models.TextField(blank=True, verbose_name='descrição complementar')),
                ('quantidade_servidores', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de servidores')),
                ('tipo_operacao', models.CharField(blank=True, max_length=100, verbose_name='tipo de operação')),
                ('quantidade_cin', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de CIN')),
                ('decisao_dg', models.CharField(choices=[('PENDENTE', 'Pendente'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=15, verbose_name='decisão da DG')),
                ('observacoes_dg', models.TextField(blank=True, verbose_name='observações da DG')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.motorista', verbose_name='motorista')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.municipio', verbose_name='município')),
                ('orgao_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.orgaoresponsavel', verbose_name='órgão responsável')),
                ('regiao', models.ForeignKey(blank=True, help_text='Preenchida automaticamente a partir do município.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.regiao', verbose_name='região')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.tipoevento', verbose_name='tipo de evento')),
            ],
            options={
                'verbose_name': 'solicitação de evento',
                'verbose_name_plural': 'solicitações de evento',
                'ordering': ['-data_solicitacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEventoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='cadastros.equipe', verbose_name='equipe')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_equipe', to='solicitacoes.solicitacaoevento', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'equipe da solicitação',
                'verbose_name_plural': 'equipes da solicitação',
            },
        ),
        migrations.AddField(
            model_name='solicitacaoevento',
            name='equipes',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes', through='solicitacoes.SolicitacaoEventoEquipe', to='cadastros.equipe', verbose_name='equipes'),
        ),
        migrations.CreateModel(
            name='SolicitacaoEventoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='cadastros.servico', verbose_name='serviço')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='solicitacoes.solicitacaoevento', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'serviço da solicitação',
                'verbose_name_plural': 'serviços da solicitação',
            },
        ),
        migrations.AddField(
            model_name='solicitacaoevento',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes', through='solicitacoes.SolicitacaoEventoServico', to='cadastros.servico', verbose_name='serviços'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoeventoequipe',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'equipe'), name='equipe_unica_por_solicitacao'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoeventoservico',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'servico'), name='servico_unico_por_solicitacao'),
        ),
    ]
