# Generated by Django 6.1 on 2026-08-29 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Rascunho criado'), ('ATUALIZACAO', 'Solicitação atualizada'), ('ENVIO', 'Solicitação enviada'), ('INICIO_ANALISE', 'Análise iniciada'), ('PLANEJAMENTO', 'Planejamento atualizado'), ('ENCAMINHAMENTO_DESPACHO', 'Encaminhada para despacho'), ('DECISAO', 'Decisão da DG registrada')], max_length=30, verbose_name='ação')),
                ('status_anterior', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DESPACHO', 'Aguardando despacho'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não atendida'), ('CANCELADA', 'Cancelada')], max_length=25, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_DESPACHO', 'Aguardando despacho'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não atendida'), ('CANCELADA', 'Cancelada')], max_length=25, verbose_name='status novo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'histórico da solicitação',
                'verbose_name_plural': 'históricos da solicitação',
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='solicitacaoevento',
            name='decidido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decidido em'),
        ),
        migrations.AddField(
            model_name='solicitacaoevento',
            name='decidido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_decididas', to=settings.AUTH_USER_MODEL, verbose_name='decidido por'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='contato',
            field=models.CharField(blank=True, max_length=100, verbose_name='contato'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='data_fim_evento',
            field=models.DateField(blank=True, null=True, verbose_name='data de fim do evento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='data_inicio_evento',
            field=models.DateField(blank=True, null=True, verbose_name='data de início do evento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='decisao_dg',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDER', 'Atender'), ('NAO_ATENDER', 'Não atender'), ('CANCELADO', 'Evento cancelado')], default='PENDENTE', max_length=15, verbose_name='decisão da DG'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='local_evento',
            field=models.CharField(blank=True, max_length=255, verbose_name='local do evento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.municipio', verbose_name='município'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='orgao_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.orgaoresponsavel', verbose_name='órgão responsável'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='solicitante_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome do solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.tipoevento', verbose_name='tipo de evento'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='tipo_operacao',
            field=models.CharField(blank=True, choices=[('ORDINARIA', 'Ordinária'), ('ITINERANTE', 'Itinerante'), ('ESPECIAL', 'Especial')], max_length=20, verbose_name='tipo de operação'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoevento',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_evento__isnull', True), ('data_fim_evento__isnull', True), ('data_fim_evento__gte', models.F('data_inicio_evento')), _connector='OR'), name='periodo_evento_valido'),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='solicitacoes.solicitacaoevento', verbose_name='solicitação'),
        ),
        migrations.AddField(
            model_name='historicosolicitacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_solicitacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
