# Generated by Django 6.1 on 2026-08-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_views_relatorio_powerbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=25, verbose_name='status anterior'),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='status_novo',
            field=models.CharField(blank=True, max_length=25, verbose_name='status novo'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_DESPACHO', 'Aguardando despacho'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=25, verbose_name='status'),
        ),
    ]
