# Generated by Django 6.1 on 2026-08-30 03:55

import django.db.models.deletion
import solicitacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_alter_historicosolicitacao_acao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=500, upload_to=solicitacoes.models._caminho_anexo, verbose_name='arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='nome original')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='solicitacoes.solicitacaoevento', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'anexo da solicitação',
                'verbose_name_plural': 'anexos da solicitação',
                'ordering': ['criado_em', 'pk'],
            },
        ),
    ]
