# Generated by Django 6.1 on 2026-08-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_unidademovel'),
        ('solicitacoes', '0012_anexosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoevento',
            name='unidade_movel_designada',
            field=models.ForeignKey(blank=True, help_text='Qual unidade móvel vai ao evento (obrigatória quando há unidade móvel).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='cadastros.unidademovel', verbose_name='unidade móvel designada'),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Rascunho criado'), ('ATUALIZACAO', 'Solicitação atualizada'), ('ENVIO', 'Solicitação enviada'), ('INICIO_ANALISE', 'Análise iniciada'), ('PLANEJAMENTO', 'Planejamento atualizado'), ('ENCAMINHAMENTO_DESPACHO', 'Encaminhada para despacho'), ('DEVOLUCAO', 'Devolvida para ajuste'), ('AJUSTE_DG', 'Quantidade ajustada pela DG'), ('DECISAO', 'Decisão da DG registrada')], max_length=30, verbose_name='ação'),
        ),
    ]
