# Generated by Django 6.1 on 2026-08-30 14:54

from django.db import migrations, models

# Só o CASE de tradução muda (mesmas colunas): CREATE OR REPLACE preserva o
# GRANT do powerbi_reader.
SQL_STATUS_DEFERIDA = """
CREATE OR REPLACE VIEW vw_solicitacoes AS
SELECT
    s.id AS solicitacao_id,
    s.status AS status_codigo,
    CASE s.status
        WHEN 'RASCUNHO' THEN 'Rascunho'
        WHEN 'AGUARDANDO_DESPACHO' THEN 'Aguardando despacho'
        WHEN 'DEVOLVIDA' THEN 'Devolvida para ajuste'
        WHEN 'DEFERIDA_EM_ANDAMENTO' THEN 'Deferida — em andamento'
        WHEN 'ATENDIDA' THEN 'Atendida'
        WHEN 'NAO_ATENDIDA' THEN 'Não atendida'
        WHEN 'CANCELADA' THEN 'Cancelada'
        ELSE s.status
    END AS status,
    s.decisao_dg AS decisao_codigo,
    CASE s.decisao_dg
        WHEN 'PENDENTE' THEN 'Pendente'
        WHEN 'ATENDER' THEN 'Atender'
        WHEN 'NAO_ATENDER' THEN 'Não atender'
        WHEN 'CANCELADO' THEN 'Evento cancelado'
        ELSE s.decisao_dg
    END AS decisao,
    s.data_solicitacao,
    s.data_inicio_evento,
    s.data_fim_evento,
    EXTRACT(YEAR FROM s.data_inicio_evento)::int AS ano_evento,
    EXTRACT(MONTH FROM s.data_inicio_evento)::int AS mes_evento,
    s.local_evento,
    m.nome AS municipio,
    r.nome AS regiao,
    e.nome AS estado,
    e.sigla AS estado_sigla,
    t.nome AS tipo_evento,
    o.nome AS orgao_responsavel,
    s.tipo_operacao AS tipo_operacao_codigo,
    CASE s.tipo_operacao
        WHEN 'DIARIA' THEN 'Diária'
        WHEN 'EXTRAJORNADA' THEN 'Extrajornada'
        ELSE s.tipo_operacao
    END AS tipo_operacao,
    s.unidade_movel,
    s.veiculo_exposicao,
    s.quantidade_servidores,
    s.quantidade_cin,
    s.solicitante_nome,
    s.solicitante_cargo_unidade,
    s.criado_em,
    s.atualizado_em,
    s.decidido_em
FROM solicitacoes_solicitacaoevento s
LEFT JOIN cadastros_municipio m ON m.id = s.municipio_id
LEFT JOIN cadastros_regiao r ON r.id = s.regiao_id
LEFT JOIN cadastros_estado e ON e.id = m.estado_id
LEFT JOIN cadastros_tipoevento t ON t.id = s.tipo_evento_id
LEFT JOIN cadastros_orgaoresponsavel o ON o.id = s.orgao_responsavel_id;
"""


def atualizar_view(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(SQL_STATUS_DEFERIDA)


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0013_solicitacaoevento_unidade_movel_designada_and_more'),
    ]

    operations = [
        # Sem status DEFERIDA_EM_ANDAMENTO no banco, reverter é inócuo.
        migrations.RunPython(atualizar_view, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Rascunho criado'), ('ATUALIZACAO', 'Solicitação atualizada'), ('ENVIO', 'Solicitação enviada'), ('INICIO_ANALISE', 'Análise iniciada'), ('PLANEJAMENTO', 'Planejamento atualizado'), ('ENCAMINHAMENTO_DESPACHO', 'Encaminhada para despacho'), ('DEVOLUCAO', 'Devolvida para ajuste'), ('AJUSTE_DG', 'Quantidade ajustada pela DG'), ('DECISAO', 'Decisão da DG registrada'), ('CONCLUSAO', 'Atendimento confirmado'), ('CANCELAMENTO', 'Evento cancelado')], max_length=30, verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGUARDANDO_DESPACHO', 'Aguardando despacho'), ('DEVOLVIDA', 'Devolvida para ajuste'), ('DEFERIDA_EM_ANDAMENTO', 'Deferida — em andamento'), ('ATENDIDA', 'Atendida'), ('NAO_ATENDIDA', 'Não atendida'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=25, verbose_name='status'),
        ),
    ]
