# Generated by Django 6.1 on 2026-08-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0015_remove_solicitacaoevento_veiculo_exposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Rascunho criado'), ('IMPORTACAO', 'Importada da planilha'), ('ATUALIZACAO', 'Solicitação atualizada'), ('ENVIO', 'Solicitação enviada'), ('INICIO_ANALISE', 'Análise iniciada'), ('PLANEJAMENTO', 'Planejamento atualizado'), ('ENCAMINHAMENTO_DESPACHO', 'Encaminhada para despacho'), ('DEVOLUCAO', 'Devolvida para ajuste'), ('AJUSTE_DG', 'Quantidade ajustada pela DG'), ('DECISAO', 'Decisão da DG registrada'), ('CONCLUSAO', 'Atendimento confirmado'), ('CANCELAMENTO', 'Evento cancelado')], max_length=30, verbose_name='ação'),
        ),
    ]
