# Generated by Django 6.1.1 on 2026-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0019_motorista_aponta_para_servidor"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicosolicitacao",
            name="alteracoes",
            field=models.JSONField(blank=True, default=list, verbose_name="alterações"),
        ),
        migrations.AlterField(
            model_name="historicosolicitacao",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Rascunho criado"),
                    ("IMPORTACAO", "Importada da planilha"),
                    ("ATUALIZACAO", "Solicitação atualizada"),
                    ("ENVIO", "Solicitação enviada"),
                    ("INICIO_ANALISE", "Análise iniciada"),
                    ("PLANEJAMENTO", "Planejamento atualizado"),
                    ("ENCAMINHAMENTO_DESPACHO", "Encaminhada para despacho"),
                    ("DEVOLUCAO", "Enviada para correção"),
                    ("REENVIO", "Alterada e reenviada para a DG"),
                    ("AJUSTE_DG", "Servidores ajustados pela DG"),
                    ("DECISAO", "Decisão da DG registrada"),
                    ("CONCLUSAO", "Atendimento confirmado"),
                    ("CANCELAMENTO", "Evento cancelado"),
                ],
                max_length=30,
                verbose_name="ação",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoevento",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("AGUARDANDO_DESPACHO", "Aguardando despacho"),
                    ("DEVOLVIDA", "Devolvida para correção"),
                    ("DEFERIDA_EM_ANDAMENTO", "Deferida — em andamento"),
                    ("ATENDIDA", "Atendida"),
                    ("NAO_ATENDIDA", "Não atendida"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="RASCUNHO",
                max_length=25,
                verbose_name="status",
            ),
        ),
    ]
