# Generated by Django 6.1.1 on 2026-09-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0020_historico_alteracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoevento",
            name="protocolo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                verbose_name="protocolo (eProtocolo)",
            ),
        ),
    ]
