# Generated by Django 6.1.1 on 2026-09-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0021_protocolo_eprotocolo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LembreteSolicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONFIRMAR_ATENDIMENTO", "Confirmar o atendimento"),
                            ("DESPACHO_PROXIMO", "Despacho com evento próximo"),
                            ("DEVOLUCAO_PARADA", "Devolução parada"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                ("referencia", models.DateField(verbose_name="data de referência")),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lembretes",
                        to="solicitacoes.solicitacaoevento",
                        verbose_name="solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "lembrete da solicitação",
                "verbose_name_plural": "lembretes da solicitação",
                "ordering": ["-enviado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitacao", "tipo", "referencia"),
                        name="lembrete_unico_por_referencia",
                    )
                ],
            },
        ),
    ]
