# Generated by Django 6.1.1 on 2026-09-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0022_lembretes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicosolicitacao",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Rascunho criado"),
                    ("IMPORTACAO", "Importada da planilha"),
                    ("ATUALIZACAO", "Solicitação atualizada"),
                    ("ENVIO", "Solicitação enviada"),
                    ("INICIO_ANALISE", "Análise iniciada"),
                    ("PLANEJAMENTO", "Planejamento atualizado"),
                    ("ENCAMINHAMENTO_DESPACHO", "Encaminhada para despacho"),
                    ("DEVOLUCAO", "Enviada para correção"),
                    ("REENVIO", "Alterada e reenviada para a DG"),
                    ("AJUSTE_DG", "Servidores ajustados pela DG"),
                    ("DECISAO", "Decisão da DG registrada"),
                    ("CONCLUSAO", "Atendimento confirmado"),
                    ("CANCELAMENTO", "Evento cancelado"),
                    ("TRANSFERENCIA", "Responsável transferido"),
                ],
                max_length=30,
                verbose_name="ação",
            ),
        ),
    ]
