# Generated by Django 6.1 on 2026-09-09 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagens_cadastros', '0003_remove_cargo_ativo_remove_combustivel_ativo_and_more'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoArtefato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_index=True, max_length=64)),
                ('formato', models.CharField(db_index=True, max_length=16)),
                ('nome_exibicao', models.CharField(blank=True, default='', help_text='Nome de exibição do arquivo, calculado na geração.', max_length=255)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('cache_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('generator_version', models.CharField(blank=True, default='', max_length=32)),
                ('engine', models.CharField(blank=True, default='', max_length=32)),
                ('arquivo', models.FileField(upload_to='documentos/gerados/%Y/%m/')),
                ('arquivo_assinado', models.FileField(blank=True, help_text='Versão assinada anexada manualmente (substitui a gerada na exibição/download).', upload_to='documentos/assinados/%Y/%m/')),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_nome_original', models.CharField(blank=True, default='', help_text='Nome do arquivo enviado pelo usuário, para exibição.', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL)),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='viagens_roteiros.roteiro')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to='viagens_cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Artefato documental',
                'verbose_name_plural': 'Artefatos documentais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAssinaturaVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='documentos/assinados/versoes/%Y/%m/')),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('artefato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_assinadas', to='documentos.documentoartefato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão assinada',
                'verbose_name_plural': 'Versões assinadas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
