# Generated by Django 6.1 on 2026-09-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('viagens_oficios', '0001_initial'),
        ('viagens_termos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefatos', to='viagens_oficios.oficio'),
        ),
        migrations.AddField(
            model_name='documentoartefato',
            name='termo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefatos', to='viagens_termos.termoautorizacao'),
        ),
    ]
