# Generated by Django 6.1 on 2026-09-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentoartefato_oficio_documentoartefato_termo'),
        ('viagens_prestacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='prestacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefatos', to='viagens_prestacoes.prestacaocontas'),
        ),
    ]
