# Generated by Django 6.1 on 2026-09-10 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentoartefato_prestacao'),
        ('viagens_cadastros', '0005_origem_legado'),
        ('viagens_oficios', '0001_initial'),
        ('viagens_prestacoes', '0004_assinaturadocumento_uniq_assinatura_codigo'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
        ('viagens_termos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='documentoartefato',
            name='legado_pk',
            field=models.UUIDField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='documentoassinaturaversao',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='documentoassinaturaversao',
            name='legado_pk',
            field=models.UUIDField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='documentoartefato',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_documentoartefato_origem'),
        ),
        migrations.AddConstraint(
            model_name='documentoassinaturaversao',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_documentoassinaturaversao_origem'),
        ),
    ]
