# Generated by Django 5.2.16 on 2026-09-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_origem_legado'),
        ('viagens_oficios', '0002_origem_legado'),
        ('viagens_prestacoes', '0006_remove_assinatura_eletronica'),
        ('viagens_termos', '0002_origem_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(db_index=True, max_length=64)),
                ('chave', models.CharField(max_length=64)),
                ('tipo', models.CharField(choices=[('paragrafo', 'Parágrafo'), ('quebra_pagina', 'Quebra de página')], default='paragrafo', max_length=16)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('conteudo_original', models.TextField(blank=True, default='')),
                ('conteudo_atual', models.TextField(blank=True, default='')),
                ('editado_manualmente', models.BooleanField(default=False)),
                ('editado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos_documentais', to='viagens_oficios.oficio')),
                ('prestacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos_documentais', to='viagens_prestacoes.prestacaocontas')),
                ('termo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos_documentais', to='viagens_termos.termoautorizacao')),
            ],
            options={
                'verbose_name': 'Bloco documental',
                'verbose_name_plural': 'Blocos documentais',
                'ordering': ['ordem', 'chave'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('oficio__isnull', False)), fields=('tipo_documento', 'oficio', 'chave'), name='documentobloco_oficio_chave'), models.UniqueConstraint(condition=models.Q(('termo__isnull', False)), fields=('tipo_documento', 'termo', 'chave'), name='documentobloco_termo_chave'), models.UniqueConstraint(condition=models.Q(('prestacao__isnull', False)), fields=('tipo_documento', 'prestacao', 'chave'), name='documentobloco_prestacao_chave')],
            },
        ),
    ]
