# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documentoartefato_ordem_servico'),
        ('viagens_planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoartefato',
            name='plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefatos', to='viagens_planos.planotrabalho'),
        ),
    ]
