# Generated by Django 6.1 on 2026-09-19 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documentoartefato_plano_trabalho'),
        ('viagens_oficios', '0005_oficio_viagem'),
        ('viagens_ordens', '0002_initial'),
        ('viagens_planos', '0003_catalogos_iniciais'),
        ('viagens_prestacoes', '0007_modelos_sem_ativo_nem_ordem'),
        ('viagens_termos', '0003_termoautorizacao_viagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobloco',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos_documentais', to='viagens_ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='documentobloco',
            name='plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos_documentais', to='viagens_planos.planotrabalho'),
        ),
        migrations.AddConstraint(
            model_name='documentobloco',
            constraint=models.UniqueConstraint(condition=models.Q(('ordem_servico__isnull', False)), fields=('tipo_documento', 'ordem_servico', 'chave'), name='documentobloco_ordem_chave'),
        ),
        migrations.AddConstraint(
            model_name='documentobloco',
            constraint=models.UniqueConstraint(condition=models.Q(('plano_trabalho__isnull', False)), fields=('tipo_documento', 'plano_trabalho', 'chave'), name='documentobloco_plano_chave'),
        ),
    ]
