# Generated by Django 6.1.1 on 2026-09-23 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0007_oficio_e_eprotocolo"),
        ("documentos", "0008_blocos_da_ordem_e_do_plano"),
        ("viagens_oficios", "0006_protocolo_automatico"),
        ("viagens_ordens", "0002_initial"),
        ("viagens_planos", "0003_catalogos_iniciais"),
        ("viagens_prestacoes", "0007_modelos_sem_ativo_nem_ordem"),
        ("viagens_termos", "0003_termoautorizacao_viagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentobloco",
            name="coffee_break_solicitacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocos_documentais",
                to="coffee_break.solicitacaocoffeebreak",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentobloco",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coffee_break_solicitacao__isnull", False)),
                fields=("tipo_documento", "coffee_break_solicitacao", "chave"),
                name="documentobloco_coffee_chave",
            ),
        ),
    ]
