# Generated by Django 6.1.1 on 2026-09-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0019_entregas_e_ocorrencias"),
        ("documentos", "0009_bloco_da_os_do_coffee_break"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoartefato",
            name="coffee_break_solicitacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artefatos",
                to="coffee_break.solicitacaocoffeebreak",
            ),
        ),
    ]
