# Generated by Django 6.1.1 on 2026-09-26 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0020_link_fornecedor"),
        ("documentos", "0010_artefato_do_coffee_break"),
        ("viagens_oficios", "0006_protocolo_automatico"),
        ("viagens_ordens", "0003_ordemservicodestino"),
        ("viagens_planos", "0006_resultados_das_atividades"),
        ("viagens_prestacoes", "0013_diario_no_celular"),
        ("viagens_termos", "0003_termoautorizacao_viagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoVersaoEditada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legado_origem",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="origem no legado"
                    ),
                ),
                (
                    "legado_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="id no legado"
                    ),
                ),
                ("tipo_documento", models.CharField(db_index=True, max_length=64)),
                ("variante", models.CharField(blank=True, default="", max_length=64)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("edicao", "Edição"),
                            ("restauracao", "Versão restaurada"),
                            ("modelo", "Voltou ao modelo"),
                        ],
                        default="edicao",
                        max_length=16,
                    ),
                ),
                ("regioes", models.JSONField(blank=True, default=dict)),
                (
                    "impressao_base",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "coffee_break_solicitacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="coffee_break.solicitacaocoffeebreak",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="viagens_oficios.oficio",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="viagens_ordens.ordemservico",
                    ),
                ),
                (
                    "plano_trabalho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="viagens_planos.planotrabalho",
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="viagens_prestacoes.prestacaocontas",
                    ),
                ),
                (
                    "restaurada_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documentos.documentoversaoeditada",
                    ),
                ),
                (
                    "termo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_editadas",
                        to="viagens_termos.termoautorizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão editada de documento",
                "verbose_name_plural": "Versões editadas de documentos",
                "ordering": ["-criado_em", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("legado_pk__isnull", False)),
                        fields=("legado_origem", "legado_pk"),
                        name="f6_documentoversaoeditada_origem",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModeloTextoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legado_origem",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="origem no legado"
                    ),
                ),
                (
                    "legado_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="id no legado"
                    ),
                ),
                ("tipo_documento", models.CharField(db_index=True, max_length=64)),
                ("chave", models.CharField(max_length=64)),
                ("texto", models.TextField(blank=True, default="")),
                (
                    "padrao_sistema",
                    models.BooleanField(
                        default=False, help_text="Voltou ao texto padrão do sistema."
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Texto de modelo de documento",
                "verbose_name_plural": "Textos de modelo de documento",
                "ordering": ["-criado_em", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["tipo_documento", "chave"],
                        name="modelotexto_tipo_chave",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("legado_pk__isnull", False)),
                        fields=("legado_origem", "legado_pk"),
                        name="f6_modelotextodocumento_origem",
                    )
                ],
            },
        ),
    ]
