# Generated by Django 6.1.1 on 2026-09-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0011_versao_editada_e_modelos_de_texto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentobloco",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("paragrafo", "Parágrafo"),
                    ("quebra_pagina", "Quebra de página"),
                    ("paragrafo_extra", "Parágrafo extra"),
                ],
                default="paragrafo",
                max_length=16,
            ),
        ),
    ]
