# Generated by Django 6.1.1 on 2026-09-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0011_versao_editada_e_modelos_de_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoassinaturaversao",
            name="assinado_em_digital",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentoassinaturaversao",
            name="assinante_nome",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="documentoassinaturaversao",
            name="conferencia",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
