# Generated by Django 6.1 on 2026-09-09 19:08

import core.uploads
import django.core.validators
import django.db.models.deletion
import viagens_prestacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagens_cadastros', '0004_configuracaosistema_assinaturaconfiguracao_and_more'),
        ('viagens_oficios', '0001_initial'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTextoRelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('motivo', 'Descrição do evento'), ('atividade', 'Objetivo da participação'), ('conclusao', 'Conclusão'), ('medidas', 'Medidas a serem adotadas pelo órgão'), ('info_complementares', 'Informações complementares')], db_index=True, max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Modelo de texto do RT',
                'verbose_name_plural': 'Modelos de texto do RT',
                'ordering': ['campo', 'ordem', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('campo', 'nome'), name='unique_modelo_texto_rt_campo_nome')],
            },
        ),
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho_assinado', models.FileField(blank=True, upload_to=viagens_prestacoes.models.prestacao_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Despacho assinado do ofício')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestacao_contas', to='viagens_oficios.oficio')),
                ('roteiro_ajustado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_roteiros.roteiro')),
            ],
            options={
                'verbose_name': 'Prestação de Contas',
                'verbose_name_plural': 'Prestações de Contas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_modo', models.CharField(choices=[('OFICIO', 'Manter motorista do ofício'), ('SERVIDOR', 'Outro servidor deste ofício'), ('OUTRO_OFICIO', 'Motorista de outro ofício')], default='OFICIO', max_length=16)),
                ('motorista_manual_nome', models.CharField(blank=True, default='', max_length=255)),
                ('motorista_manual_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('motorista_oficio_referencia', models.CharField(blank=True, default='', help_text='Referência no formato número/ano (ex.: 15/2026).', max_length=16, verbose_name='Ofício do motorista')),
                ('motorista_protocolo_ref', models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo do motorista')),
                ('viatura_modo', models.CharField(choices=[('OFICIO', 'Manter a viatura do ofício'), ('BANCO', 'Selecionar do cadastro'), ('MANUAL', 'Preencher manualmente')], default='OFICIO', max_length=10)),
                ('viatura_manual_modelo', models.CharField(blank=True, default='', max_length=120)),
                ('viatura_manual_placa', models.CharField(blank=True, default='', max_length=8)),
                ('viatura_manual_tipo', models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='', max_length=20)),
                ('viatura_manual_combustivel', models.CharField(blank=True, default='', max_length=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista_servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Motorista (servidor do ofício)')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.viatura', verbose_name='Viatura (cadastro)')),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diario_bordo', to='viagens_prestacoes.prestacaocontas')),
            ],
            options={
                'verbose_name': 'Diário de Bordo',
                'verbose_name_plural': 'Diários de Bordo',
            },
        ),
        migrations.CreateModel(
            name='PrestacaoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao', models.CharField(blank=True, default='', max_length=60, verbose_name='Número da solicitação')),
                ('diaria_valor_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diária recebida por este servidor')),
                ('diaria_valor_override_observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Observação sobre o valor recebido')),
                ('data_liberacao_diarias', models.DateField(blank=True, null=True, verbose_name='Data de liberação das diárias')),
                ('prazo_limite_saque', models.DateField(blank=True, null=True, verbose_name='Prazo limite para saque')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preenchimento', 'Em preenchimento'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=30)),
                ('arquivada', models.BooleanField(default=False)),
                ('arquivada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('removida_em', models.DateTimeField(blank=True, null=True, verbose_name='Removida da equipe em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores_prestacao', to='viagens_prestacoes.prestacaocontas')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_servidor', to='viagens_cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Servidor da prestação',
                'verbose_name_plural': 'Servidores da prestação',
                'ordering': ['prestacao', 'pk'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PrestacaoDocumentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('despacho', 'Despacho assinado do ofício'), ('oficio_assinado', 'Ofício assinado'), ('comprovante', 'Comprovante de saque/transferência'), ('rt_assinado', 'Relatório técnico assinado'), ('db_assinado', 'Diário de bordo assinado')], db_index=True, max_length=20)),
                ('arquivo', models.FileField(upload_to=viagens_prestacoes.models.prestacao_documento_anexo_upload_to, validators=[core.uploads.validate_private_document_upload])),
                ('arquivo_original', models.FileField(blank=True, help_text='PDF como enviado, antes do carimbo. Origem de todo recarimbo.', upload_to=viagens_prestacoes.models.prestacao_anexo_original_upload_to)),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='viagens_prestacoes.prestacaocontas')),
                ('servidor_prestacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='viagens_prestacoes.prestacaoservidor')),
            ],
            options={
                'verbose_name': 'Anexo da prestação de contas',
                'verbose_name_plural': 'Anexos da prestação de contas',
                'ordering': ['tipo', 'criado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CarimboSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.PositiveSmallIntegerField(default=0)),
                ('x', models.FloatField(help_text='Fração da largura, 0 = borda esquerda.')),
                ('y', models.FloatField(help_text='Fração da altura, 0 = topo da página.')),
                ('tamanho', models.FloatField(default=0.012)),
                ('ajustado_manualmente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='viagens_prestacoes.prestacaodocumentoanexo')),
                ('servidor_prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos_solicitacao', to='viagens_prestacoes.prestacaoservidor')),
            ],
            options={
                'verbose_name': 'Carimbo do número de solicitação',
                'verbose_name_plural': 'Carimbos do número de solicitação',
                'ordering': ['pagina', 'y', 'x', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, default='')),
                ('diaria', models.CharField(blank=True, default='', max_length=255)),
                ('translado', models.CharField(blank=True, default='', max_length=255)),
                ('combustivel', models.CharField(blank=True, default='', max_length=255)),
                ('passagem', models.CharField(blank=True, default='', max_length=255)),
                ('atividade', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('medidas', models.TextField(blank=True, default='')),
                ('info_complementares', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_tecnico', to='viagens_prestacoes.prestacaocontas')),
            ],
            options={
                'verbose_name': 'Relatório Técnico',
                'verbose_name_plural': 'Relatórios Técnicos',
            },
        ),
        migrations.CreateModel(
            name='DiarioBordoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('km_final', models.PositiveIntegerField(blank=True, null=True)),
                ('abastecimento', models.BooleanField(blank=True, null=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='viagens_prestacoes.diariobordo')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diario_bordo_trechos', to='viagens_roteiros.roteirotrecho')),
            ],
            options={
                'verbose_name': 'Trecho do diário de bordo',
                'verbose_name_plural': 'Trechos do diário de bordo',
                'ordering': ['diario', 'ordem', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('diario', 'ordem'), name='diario_trecho_ordem_unique'), models.CheckConstraint(condition=models.Q(('km_final__gte', models.F('km_inicial'))), name='diario_trecho_km_ordenado', violation_error_message='O km final não pode ser menor que o km inicial.')],
            },
        ),
        migrations.AddIndex(
            model_name='prestacaoservidor',
            index=models.Index(fields=['arquivada', 'finalizada', 'data_liberacao_diarias'], name='prest_serv_aba_idx'),
        ),
        migrations.AddIndex(
            model_name='prestacaoservidor',
            index=models.Index(fields=['status'], name='prest_serv_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoservidor',
            constraint=models.UniqueConstraint(fields=('prestacao', 'servidor'), name='unique_servidor_por_prestacao'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoservidor',
            constraint=models.CheckConstraint(condition=models.Q(('diaria_valor_override__gt', 0)), name='prest_serv_diaria_recebida_positiva'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoservidor',
            constraint=models.CheckConstraint(condition=models.Q(('prazo_limite_saque__gte', models.F('data_liberacao_diarias'))), name='prest_serv_prazo_apos_liberacao'),
        ),
        migrations.AddConstraint(
            model_name='carimbosolicitacao',
            constraint=models.UniqueConstraint(fields=('anexo', 'servidor_prestacao'), name='carimbo_unico_por_servidor_no_anexo'),
        ),
    ]
