# Generated by Django 6.1 on 2026-09-09 19:22

import core.uploads
import django.core.validators
import viagens_prestacoes.arquivos
import viagens_prestacoes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_prestacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaocontas',
            name='despacho_assinado',
            field=viagens_prestacoes.arquivos.ArquivoPrivadoField(blank=True, upload_to=viagens_prestacoes.models.prestacao_documento_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Despacho assinado do ofício'),
        ),
        migrations.AlterField(
            model_name='prestacaodocumentoanexo',
            name='arquivo',
            field=viagens_prestacoes.arquivos.ArquivoPrivadoField(upload_to=viagens_prestacoes.models.prestacao_documento_anexo_upload_to, validators=[core.uploads.validate_private_document_upload]),
        ),
        migrations.AlterField(
            model_name='prestacaodocumentoanexo',
            name='arquivo_original',
            field=viagens_prestacoes.arquivos.ArquivoPrivadoField(blank=True, help_text='PDF como enviado, antes do carimbo. Origem de todo recarimbo.', upload_to=viagens_prestacoes.models.prestacao_anexo_original_upload_to),
        ),
    ]
