# Generated by Django 6.1 on 2026-09-09 20:25

import django.db.models.deletion
import viagens_prestacoes.arquivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_cadastros', '0004_configuracaosistema_assinaturaconfiguracao_and_more'),
        ('viagens_prestacoes', '0002_alter_prestacaocontas_despacho_assinado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rt', 'Relatório Técnico'), ('db', 'Diário de Bordo')], db_index=True, max_length=4)),
                ('nome_esperado', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinada', 'Assinada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('link_token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('link_criado_em', models.DateTimeField(blank=True, null=True)),
                ('link_expira_em', models.DateTimeField(blank=True, null=True)),
                ('identidade_confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('arquivo_origem', viagens_prestacoes.arquivos.ArquivoPrivadoField(blank=True, upload_to='viagens_prestacoes/assinaturas/')),
                ('modo', models.CharField(blank=True, choices=[('fonte', 'Fonte'), ('desenho', 'Desenho')], default='', max_length=10)),
                ('fonte', models.CharField(blank=True, default='', max_length=60)),
                ('assinatura_png', viagens_prestacoes.arquivos.ArquivoPrivadoField(blank=True, upload_to='viagens_prestacoes/assinaturas/')),
                ('pagina', models.PositiveIntegerField(default=0)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('largura', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('arquivo_assinado', viagens_prestacoes.arquivos.ArquivoPrivadoField(blank=True, upload_to='viagens_prestacoes/assinaturas/')),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_ip', models.CharField(blank=True, default='', max_length=64)),
                ('codigo_verificacao', models.CharField(blank=True, default='', max_length=12)),
                ('hash_documento', models.CharField(blank=True, default='', max_length=64)),
                ('hash_assinado', models.CharField(blank=True, default='', max_length=64)),
                ('cpf_prefixo_hash', models.CharField(blank=True, default='', max_length=64)),
                ('tentativas_identidade', models.PositiveSmallIntegerField(default=0)),
                ('bloqueada_ate', models.DateTimeField(blank=True, null=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='viagens_prestacoes.prestacaocontas')),
                ('servidor_prestacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='viagens_prestacoes.prestacaoservidor')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_documentos', to='viagens_cadastros.servidor')),
            ],
            options={
                'verbose_name': 'Assinatura de documento',
                'verbose_name_plural': 'Assinaturas de documentos',
                'ordering': ['prestacao', 'tipo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('servidor_prestacao__isnull', True), models.Q(('status', 'cancelada'), _negated=True)), fields=('prestacao', 'tipo'), name='uniq_assinatura_prestacao_tipo'), models.UniqueConstraint(condition=models.Q(('servidor_prestacao__isnull', False), models.Q(('status', 'cancelada'), _negated=True)), fields=('servidor_prestacao', 'tipo'), name='uniq_assinatura_servidor_tipo')],
            },
        ),
    ]
