# Generated by Django 6.1 on 2026-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_cadastros', '0004_configuracaosistema_assinaturaconfiguracao_and_more'),
        ('viagens_prestacoes', '0003_assinaturadocumento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assinaturadocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_verificacao', ''), _negated=True), fields=('codigo_verificacao',), name='uniq_assinatura_codigo'),
        ),
    ]
