# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_cadastros', '0005_origem_legado'),
        ('viagens_oficios', '0002_origem_legado'),
        ('viagens_prestacoes', '0004_assinaturadocumento_uniq_assinatura_codigo'),
        ('viagens_roteiros', '0002_rota_persistida_e_tempos_do_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturadocumento',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='carimbosolicitacao',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='carimbosolicitacao',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='diariobordotrecho',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='diariobordotrecho',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='modelotextorelatoriotecnico',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='modelotextorelatoriotecnico',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='prestacaodocumentoanexo',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='prestacaodocumentoanexo',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='prestacaoservidor',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='prestacaoservidor',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='relatoriotecnico',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='assinaturadocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_assinaturadocumento_origem'),
        ),
        migrations.AddConstraint(
            model_name='carimbosolicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_carimbosolicitacao_origem'),
        ),
        migrations.AddConstraint(
            model_name='diariobordo',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_diariobordo_origem'),
        ),
        migrations.AddConstraint(
            model_name='diariobordotrecho',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_diariobordotrecho_origem'),
        ),
        migrations.AddConstraint(
            model_name='modelotextorelatoriotecnico',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_modelotextorelatoriotecnico_origem'),
        ),
        migrations.AddConstraint(
            model_name='prestacaocontas',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_prestacaocontas_origem'),
        ),
        migrations.AddConstraint(
            model_name='prestacaodocumentoanexo',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_prestacaodocumentoanexo_origem'),
        ),
        migrations.AddConstraint(
            model_name='prestacaoservidor',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_prestacaoservidor_origem'),
        ),
        migrations.AddConstraint(
            model_name='relatoriotecnico',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_relatoriotecnico_origem'),
        ),
    ]
