# Generated by Django 6.1 on 2026-09-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_prestacoes', '0005_origem_legado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assinaturadocumento',
            name='uniq_assinatura_prestacao_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='assinaturadocumento',
            name='uniq_assinatura_servidor_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='assinaturadocumento',
            name='uniq_assinatura_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='assinaturadocumento',
            name='f6_assinaturadocumento_origem',
        ),
        migrations.DeleteModel(
            name='AssinaturaDocumento',
        ),
    ]
