# Generated by Django 5.2.16 on 2026-09-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_prestacoes', '0006_remove_assinatura_eletronica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelotextorelatoriotecnico',
            options={'ordering': ['campo', 'nome'], 'verbose_name': 'Modelo de texto do RT', 'verbose_name_plural': 'Modelos de texto do RT'},
        ),
        migrations.RemoveField(
            model_name='modelotextorelatoriotecnico',
            name='ordem',
        ),
    ]
