# Generated by Django 6.1.1 on 2026-09-25 05:24

import django.db.models.deletion
import viagens_prestacoes.arquivos
import viagens_prestacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_oficios", "0006_protocolo_automatico"),
        ("viagens_prestacoes", "0007_modelos_sem_ativo_nem_ordem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="data_operacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="data da operação"
            ),
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="operacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("saque", "Saque"),
                    ("transferencia", "Transferência"),
                    ("pix", "Pix"),
                    ("ted", "TED"),
                    ("doc", "DOC"),
                    ("deposito", "Depósito"),
                ],
                default="",
                max_length=20,
                verbose_name="operação",
            ),
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="paginas_origem",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="páginas no processo",
            ),
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="valor da operação",
            ),
        ),
        migrations.CreateModel(
            name="ImportacaoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legado_origem",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="origem no legado"
                    ),
                ),
                (
                    "legado_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="id no legado"
                    ),
                ),
                (
                    "arquivo",
                    viagens_prestacoes.arquivos.ArquivoPrivadoField(
                        upload_to=viagens_prestacoes.models.importacao_processo_upload_to,
                        verbose_name="processo enviado",
                    ),
                ),
                (
                    "nome_original",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="SHA-256 do arquivo"
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="protocolo lido",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("analisada", "Aguardando conferência"),
                            ("aplicada", "Aplicada"),
                            ("descartada", "Descartada"),
                        ],
                        db_index=True,
                        default="analisada",
                        max_length=20,
                    ),
                ),
                ("plano", models.JSONField(blank=True, default=dict)),
                ("resultado", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("aplicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importacoes_processo",
                        to="viagens_oficios.oficio",
                    ),
                ),
                (
                    "prestacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importacoes",
                        to="viagens_prestacoes.prestacaocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de processo",
                "verbose_name_plural": "Importações de processo",
                "ordering": ["-criado_em", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="importacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anexos",
                to="viagens_prestacoes.importacaoprocesso",
            ),
        ),
        migrations.AddConstraint(
            model_name="prestacaodocumentoanexo",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)), name="prest_anexo_valor_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="importacaoprocesso",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado_pk__isnull", False)),
                fields=("legado_origem", "legado_pk"),
                name="f6_importacaoprocesso_origem",
            ),
        ),
    ]
