# Generated by Django 6.1.1 on 2026-09-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0008_importacao_processo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestacaodocumentoanexo",
            options={
                "default_manager_name": "objects",
                "ordering": ["tipo", "criado_em", "pk"],
                "verbose_name": "Anexo da prestação de contas",
                "verbose_name_plural": "Anexos da prestação de contas",
            },
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="removido_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="removido em"
            ),
        ),
        migrations.AddField(
            model_name="prestacaodocumentoanexo",
            name="removido_motivo",
            field=models.CharField(
                blank=True,
                choices=[("excluido", "Removido"), ("substituido", "Substituído")],
                default="",
                max_length=12,
                verbose_name="motivo da remoção",
            ),
        ),
    ]
