# Generated by Django 6.1.1 on 2026-09-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0009_anexo_versoes_anteriores"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaoservidor",
            name="justificativa_finalizacao",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Justificativa para finalizar com pendências",
            ),
        ),
    ]
