# Generated by Django 6.1.1 on 2026-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0010_justificativa_finalizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaoservidor",
            name="decidida_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aprovada ou devolvida em"
            ),
        ),
        migrations.AddField(
            model_name="prestacaoservidor",
            name="enviada_em",
            field=models.DateField(blank=True, null=True, verbose_name="Enviada em"),
        ),
        migrations.AddField(
            model_name="prestacaoservidor",
            name="motivo_devolucao",
            field=models.TextField(
                blank=True, default="", verbose_name="Motivo da devolução"
            ),
        ),
        migrations.AddField(
            model_name="prestacaoservidor",
            name="protocolo_envio",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Protocolo ou e-mail do envio",
            ),
        ),
        migrations.AlterField(
            model_name="prestacaoservidor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_preenchimento", "Em preenchimento"),
                    ("enviada", "Enviada"),
                    ("aprovada", "Aprovada"),
                    ("reprovada", "Devolvida"),
                ],
                default="pendente",
                max_length=30,
            ),
        ),
    ]
