# Generated by Django 6.1.1 on 2026-09-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0011_envio_ao_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaoservidor",
            name="ajuste_pacote",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Ajuste manual do pacote final"
            ),
        ),
    ]
