# Generated by Django 6.1.1 on 2026-09-26 05:59

import django.db.models.deletion
import viagens_prestacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0012_ajuste_do_pacote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkDiarioCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=viagens_prestacoes.models._token_do_link,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expira_em", models.DateTimeField(verbose_name="vale até")),
                (
                    "revogado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revogado em"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ultimo_acesso_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último acesso"
                    ),
                ),
                (
                    "ultimo_envio_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último lançamento recebido"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_campo",
                        to="viagens_prestacoes.diariobordo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link do diário no celular",
                "verbose_name_plural": "Links do diário no celular",
                "ordering": ["-criado_em", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoDiarioCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente_id",
                    models.CharField(
                        max_length=64, verbose_name="id gerado no celular"
                    ),
                ),
                ("dados", models.JSONField(blank=True, default=dict)),
                (
                    "situacao",
                    models.CharField(
                        choices=[("gravado", "Gravado"), ("recusado", "Recusado")],
                        max_length=10,
                    ),
                ),
                ("mensagem", models.CharField(blank=True, default="", max_length=255)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancamentos_campo",
                        to="viagens_prestacoes.diariobordo",
                    ),
                ),
                (
                    "linha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="viagens_prestacoes.diariobordotrecho",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos",
                        to="viagens_prestacoes.linkdiariocampo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento do diário no celular",
                "verbose_name_plural": "Lançamentos do diário no celular",
                "ordering": ["recebido_em", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("diario", "cliente_id"),
                        name="lancamento_campo_unico_por_diario",
                    )
                ],
            },
        ),
    ]
