# Generated by Django 6.1.1 on 2026-09-26 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0013_diario_no_celular"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentodiariocampo",
            name="legado_origem",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="origem no legado"
            ),
        ),
        migrations.AddField(
            model_name="lancamentodiariocampo",
            name="legado_pk",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="id no legado"
            ),
        ),
        migrations.AddField(
            model_name="linkdiariocampo",
            name="legado_origem",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="origem no legado"
            ),
        ),
        migrations.AddField(
            model_name="linkdiariocampo",
            name="legado_pk",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="id no legado"
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentodiariocampo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado_pk__isnull", False)),
                fields=("legado_origem", "legado_pk"),
                name="f6_lancamentodiariocampo_origem",
            ),
        ),
        migrations.AddConstraint(
            model_name="linkdiariocampo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado_pk__isnull", False)),
                fields=("legado_origem", "legado_pk"),
                name="f6_linkdiariocampo_origem",
            ),
        ),
    ]
