# Generated by Django 6.1.1 on 2026-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0014_diario_celular_origem_legado"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacaocontas",
            name="protocolo_consultado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Consultado no eProtocolo em"
            ),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="protocolo_local",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Setor atual no eProtocolo",
            ),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="protocolo_movimentado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última movimentação no eProtocolo"
            ),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="protocolo_simulado",
            field=models.BooleanField(default=False, verbose_name="Consulta simulada"),
        ),
        migrations.AddField(
            model_name="prestacaocontas",
            name="protocolo_situacao",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Situação no eProtocolo",
            ),
        ),
    ]
