# Generated by Django 6.1.1 on 2026-09-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0014_diario_celular_origem_legado"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelotextorelatoriotecnico",
            name="is_padrao",
            field=models.BooleanField(
                default=False, verbose_name="usar como padrão do campo"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelotextorelatoriotecnico",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_padrao", True)),
                fields=("campo",),
                name="viagens_rt_modelo_padrao_por_campo",
            ),
        ),
    ]
