# Generated by Django 6.1.1 on 2026-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_prestacoes", "0015_andamento_eprotocolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="diariobordotrecho",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
