# Generated by Django 6.1 on 2026-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False, verbose_name='precisa trocar a senha no próximo acesso'),
        ),
    ]
