# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_setor_modulo_user_setores'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='user',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_user_origem'),
        ),
    ]
