# Generated by Django 6.1.1 on 2026-09-26 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_origem_legado"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False, max_length=64, unique=True, verbose_name="token"
                    ),
                ),
                (
                    "gerado_em",
                    models.DateTimeField(auto_now=True, verbose_name="gerado em"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinatura_agenda",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "assinatura da agenda",
                "verbose_name_plural": "assinaturas da agenda",
            },
        ),
    ]
