# Generated by Django 6.1.1 on 2026-09-26 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_assinatura_agenda"),
        (
            "viagens_cadastros",
            "0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="servidor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario",
                to="viagens_cadastros.servidor",
                verbose_name="servidor correspondente",
            ),
        ),
    ]
