# Generated by Django 6.1.1 on 2026-09-27 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_servidor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PautaSemanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        verbose_name="receber a pauta da semana por e-mail",
                    ),
                ),
                (
                    "enviada_para_semana",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="semana da última pauta enviada",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauta_semanal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "pauta semanal",
                "verbose_name_plural": "pautas semanais",
            },
        ),
    ]
