# Generated by Django 6.1 on 2026-09-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0009_municipio_coordenadas'),
        ('viagens_cadastros', '0004_configuracaosistema_assinaturaconfiguracao_and_more'),
        ('viagens_oficios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cancelado', models.BooleanField(default=False, verbose_name='cancelado')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('destinos_extras', models.JSONField(blank=True, default=list, verbose_name='Destinos adicionais')),
                ('data_evento_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos_autorizacao', to='cadastros.municipio', verbose_name='Cidade do destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='UF do destino')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='viagens_oficios.oficio', verbose_name='Oficio vinculado')),
                ('servidores', models.ManyToManyField(blank=True, related_name='termos_autorizacao', to='viagens_cadastros.servidor', verbose_name='Servidores')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_autorizacao', to='viagens_cadastros.viatura', verbose_name='Viatura')),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_evento_fim__gte', models.F('data_evento_inicio'))), name='termo_periodo_ordenado')],
            },
        ),
    ]
