# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('viagens_cadastros', '0005_origem_legado'),
        ('viagens_oficios', '0002_origem_legado'),
        ('viagens_termos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoautorizacao',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='termoautorizacao',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_termoautorizacao_origem'),
        ),
    ]
