# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_termos', '0002_origem_legado'),
        ('viagens_viagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoautorizacao',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termos_autorizacao', to='viagens_viagem.viagem', verbose_name='Viagem'),
        ),
    ]
