# Generated by Django 6.1.1 on 2026-09-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("PAINEL", "Painel do sistema"),
                            ("WHATSAPP", "WhatsApp"),
                        ],
                        default="PAINEL",
                        max_length=20,
                        verbose_name="canal",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas_assistente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversa do assistente",
                "verbose_name_plural": "conversas do assistente",
                "ordering": ["-atualizado_em"],
            },
        ),
        migrations.CreateModel(
            name="AcaoPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ferramenta",
                    models.CharField(max_length=60, verbose_name="ferramenta"),
                ),
                (
                    "rascunho",
                    models.JSONField(blank=True, default=dict, verbose_name="rascunho"),
                ),
                (
                    "extraidos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="extraídos do pedido"
                    ),
                ),
                (
                    "aguardando_campo",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="campo em pergunta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COLETANDO", "Coletando dados"),
                            ("AGUARDANDO", "Aguardando confirmação"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="COLETANDO",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "resultado",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resultado"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "resolvido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolvido em"
                    ),
                ),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_assistente_resolvidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resolvido por",
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes",
                        to="assistente.conversa",
                        verbose_name="conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "ação pendente do assistente",
                "verbose_name_plural": "ações pendentes do assistente",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        choices=[("PESSOA", "Pessoa"), ("ASSISTENTE", "Assistente")],
                        max_length=20,
                        verbose_name="autor",
                    ),
                ),
                ("texto", models.TextField(verbose_name="texto")),
                (
                    "ferramenta",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="ferramenta"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="assistente.conversa",
                        verbose_name="conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem do assistente",
                "verbose_name_plural": "mensagens do assistente",
                "ordering": ["criado_em", "pk"],
            },
        ),
    ]
