# Generated by Django 6.1.1 on 2026-09-20 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistente", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemRecebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="id da mensagem"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="número de origem"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEXTO", "Texto"),
                            ("AUDIO", "Áudio"),
                            ("OUTRO", "Outro"),
                        ],
                        default="TEXTO",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("texto", models.TextField(blank=True, verbose_name="texto")),
                (
                    "media_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="id da mídia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSADA", "Processada"),
                            ("IGNORADA", "Ignorada"),
                            ("ERRO", "Erro"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                (
                    "recebida_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebida em"),
                ),
                (
                    "processada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processada em"
                    ),
                ),
                (
                    "conversa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens_whatsapp",
                        to="assistente.conversa",
                        verbose_name="conversa",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem recebida do WhatsApp",
                "verbose_name_plural": "mensagens recebidas do WhatsApp",
                "ordering": ["recebida_em", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MensagemEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="número de destino"
                    ),
                ),
                ("texto", models.TextField(verbose_name="texto")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENVIADA", "Enviada"),
                            ("ERRO", "Erro"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "tentativas",
                    models.PositiveIntegerField(default=0, verbose_name="tentativas"),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="id da mensagem"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "enviada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enviada em"
                    ),
                ),
                (
                    "resposta_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respostas",
                        to="assistente.mensagemrecebida",
                        verbose_name="resposta a",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem enviada pelo WhatsApp",
                "verbose_name_plural": "mensagens enviadas pelo WhatsApp",
                "ordering": ["criada_em", "pk"],
            },
        ),
        migrations.CreateModel(
            name="VinculoWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="número (E.164, só dígitos)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "ultima_entrada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última mensagem recebida"
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vinculos_whatsapp_autorizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autorizado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_whatsapp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo de WhatsApp",
                "verbose_name_plural": "vínculos de WhatsApp",
                "ordering": ["numero"],
            },
        ),
    ]
