# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('viagens_cadastros', '0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more'),
        ('viagens_oficios', '0004_status_finalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoNumeroLacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(db_index=True)),
                ('numero', models.PositiveIntegerField()),
                ('liberado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Ordem de Serviço liberado',
                'verbose_name_plural': 'Números de Ordem de Serviço liberados',
                'ordering': ['ano', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cancelado', models.BooleanField(default=False, verbose_name='cancelado')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('legado_origem', models.CharField(blank=True, max_length=50, verbose_name='origem no legado')),
                ('legado_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado')),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data_evento_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial do evento')),
                ('data_evento_fim', models.DateField(blank=True, null=True, verbose_name='Data final do evento')),
                ('tipo_necessidade', models.CharField(choices=[('PADRAO', 'Padrão / texto livre'), ('OPERACAO_RETORNO_POSTERIOR', 'Operação policial - um dia posterior'), ('CAMINHAO', 'Caminhão - dois dias antes e depois'), ('MICROONIBUS', 'Micro-ônibus'), ('CERIMONIAL_ANTECIPADO', 'Cerimonial - ida antecipada')], default='PADRAO', max_length=40, verbose_name='Tipo de necessidade')),
                ('funcoes_servidores', models.JSONField(blank=True, default=dict, verbose_name='Funções dos servidores')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('apoio_cerimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Apoio de cerimonial')),
                ('apoio_escolta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Apoio de escolta')),
                ('apoio_montagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Apoio de montagem')),
                ('apoio_preparacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Apoio de preparação')),
                ('coordenador_cerimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Coordenação de cerimonial')),
                ('destinos', models.ManyToManyField(blank=True, related_name='ordens_servico', to='cadastros.municipio', verbose_name='Destinos')),
                ('motorista_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Motorista')),
                ('oficios', models.ManyToManyField(blank=True, related_name='ordens_servico', to='viagens_oficios.oficio', verbose_name='Ofícios vinculados')),
                ('servidores', models.ManyToManyField(blank=True, related_name='ordens_servico', to='viagens_cadastros.servidor', verbose_name='Servidores')),
                ('tecnico_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-ano', '-numero'],
            },
        ),
    ]
