# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagens_ordens', '0001_initial'),
        ('viagens_viagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='viagens_viagem.viagem', verbose_name='Viagem'),
        ),
        migrations.AddConstraint(
            model_name='ordemserviconumerolacuna',
            constraint=models.UniqueConstraint(fields=('ano', 'numero'), name='os_lacuna_ano_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_ordemservico_origem'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('ano', 'numero'), name='viagens_ordem_servico_ano_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('data_evento_fim__gte', models.F('data_evento_inicio'))), name='os_periodo_ordenado'),
        ),
    ]
