# Generated by Django 6.1 on 2026-09-10 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('areas', models.JSONField()),
                ('opcoes', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('desfeito_em', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('concluida_em', models.DateTimeField(auto_now=True)),
                ('relatorio', models.JSONField(default=dict)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='migracao_legado.lote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lote', 'nome'), name='f6_etapa_lote_unica')],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=30)),
                ('tabela', models.CharField(max_length=100)),
                ('origem_pk', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=100)),
                ('destino_pk', models.CharField(max_length=64)),
                ('criado', models.BooleanField(default=True)),
                ('antes', models.JSONField(default=dict)),
                ('depois', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('arquivos', models.JSONField(default=list)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='migracao_legado.lote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tabela', 'origem_pk'), name='f6_registro_origem_unica')],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('destino_pk', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=64)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='migracao_legado.lote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('modelo', 'destino_pk'), name='f6_vinculo_destino_unico')],
            },
        ),
    ]
