# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
import viagens_viagem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('viagens_cadastros', '0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legado_origem', models.CharField(blank=True, max_length=50, verbose_name='origem no legado')),
                ('legado_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Tipo de viagem',
                'verbose_name_plural': 'Tipos de viagem',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_tipoviagem_origem')],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cancelado', models.BooleanField(default=False, verbose_name='cancelado')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('legado_origem', models.CharField(blank=True, max_length=50, verbose_name='origem no legado')),
                ('legado_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado')),
                ('titulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição/objetivo')),
                ('destinos_extras', models.JSONField(blank=True, default=list, verbose_name='Destinos adicionais')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário inicial')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário final')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preparacao', 'Em preparação'), ('documentos_gerados', 'Documentos gerados'), ('em_execucao', 'Em execução'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=30)),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='UF do destino')),
                ('destino_municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='cadastros.municipio', verbose_name='Município do destino')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_responsavel', to='viagens_cadastros.servidor', verbose_name='Responsável')),
                ('tipos', models.ManyToManyField(blank=True, related_name='viagens', to='viagens_viagem.tipoviagem', verbose_name='Tipos da viagem')),
                ('unidade_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='viagens_cadastros.unidade', verbose_name='Unidade responsável')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ViagemDocumentoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legado_origem', models.CharField(blank=True, max_length=50, verbose_name='origem no legado')),
                ('legado_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado')),
                ('arquivo', models.FileField(upload_to=viagens_viagem.models.viagem_solicitacao_upload_to)),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_solicitacao', to='viagens_viagem.viagem')),
            ],
            options={
                'verbose_name': 'Documento de solicitação da viagem',
                'verbose_name_plural': 'Documentos de solicitação da viagem',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_viagem_origem'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='viagem_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='viagemdocumentosolicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_viagemdocumentosolicitacao_origem'),
        ),
    ]
