# Generated by Django 6.1.1 on 2026-09-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_origem_legado"),
        ("cadastros", "0013_modelo_por_tipo_de_evento"),
        ("viagens_viagem", "0002_tipos_iniciais"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens",
                to="accounts.setor",
                verbose_name="Ambiente (setor)",
            ),
        ),
        migrations.CreateModel(
            name="EquipePrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="servidores designados"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.equipe",
                        verbose_name="equipe",
                    ),
                ),
                (
                    "viagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes_previstas",
                        to="viagens_viagem.viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe prevista da viagem",
                "verbose_name_plural": "Equipes previstas da viagem",
                "ordering": ["equipe__nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("viagem", "equipe"), name="viagem_equipe_prevista_unica"
                    )
                ],
            },
        ),
    ]
