# Generated by Django 6.1.1 on 2026-09-26 05:50

import core.uploads
import viagens_viagem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_viagem", "0003_ambiente_e_equipes_previstas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viagemdocumentosolicitacao",
            name="arquivo",
            field=models.FileField(
                upload_to=viagens_viagem.models.viagem_solicitacao_upload_to,
                validators=[core.uploads.validate_private_document_upload],
            ),
        ),
    ]
