# Generated by Django 6.1.1 on 2026-09-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0024_endereco_do_evento"),
        ("viagens_viagem", "0004_anexo_solicitacao_validado"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="solicitacoes_juntadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="viagens_juntadas",
                to="solicitacoes.solicitacaoevento",
                verbose_name="Outros eventos atendidos nesta viagem",
            ),
        ),
    ]
