# Generated by Django 6.1 on 2026-08-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, unique=True, verbose_name="nome"),
                ),
                (
                    "sigla",
                    models.CharField(blank=True, max_length=50, verbose_name="sigla"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "unidade",
                "verbose_name_plural": "unidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, unique=True, verbose_name="nome"),
                ),
                (
                    "is_padrao",
                    models.BooleanField(default=False, verbose_name="padrão"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "cargo",
                "verbose_name_plural": "cargos",
                "ordering": ["nome"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_padrao", True)),
                        fields=("is_padrao",),
                        name="viagens_cargo_padrao_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Combustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, unique=True, verbose_name="nome"),
                ),
                (
                    "is_padrao",
                    models.BooleanField(default=False, verbose_name="padrão"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "combustível",
                "verbose_name_plural": "combustíveis",
                "ordering": ["nome"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_padrao", True)),
                        fields=("is_padrao",),
                        name="viagens_combustivel_padrao_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TabelaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "faixa",
                    models.CharField(
                        choices=[
                            ("INTERIOR", "Interior"),
                            ("CAPITAL", "Capital"),
                            ("BRASILIA", "Brasília"),
                        ],
                        max_length=20,
                        verbose_name="faixa",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(
                        help_text="Viagens com saída a partir desta data usam estes valores.",
                        verbose_name="vigente a partir de",
                    ),
                ),
                (
                    "valor_24h",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="diária de 24 horas",
                    ),
                ),
                (
                    "valor_15",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="15%",
                    ),
                ),
                (
                    "valor_30",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="30%",
                    ),
                ),
            ],
            options={
                "verbose_name": "tabela de diárias",
                "verbose_name_plural": "tabelas de diárias",
                "ordering": ["-vigencia_inicio", "faixa"],
                "indexes": [
                    models.Index(
                        fields=["faixa", "-vigencia_inicio"],
                        name="viagens_tabdiaria_busca_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faixa", "vigencia_inicio"),
                        name="viagens_tabela_diaria_faixa_vigencia_unica",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_24h__gt", 0)),
                        name="viagens_tabela_diaria_valor_24h_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_15__gt", 0)),
                        name="viagens_tabela_diaria_valor_15_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_30__gt", 0)),
                        name="viagens_tabela_diaria_valor_30_positivo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "legado_origem",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="origem no legado"
                    ),
                ),
                (
                    "legado_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="id no legado"
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("COMPLETO", "Completo")],
                        default="RASCUNHO",
                        editable=False,
                        max_length=20,
                        verbose_name="situação do cadastro",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=30, verbose_name="RG")),
                (
                    "sem_rg",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="não possui RG"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="telefone"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servidores",
                        to="viagens_cadastros.cargo",
                        verbose_name="cargo",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servidores",
                        to="viagens_cadastros.unidade",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "servidor",
                "verbose_name_plural": "servidores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Viatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "placa",
                    models.CharField(max_length=7, unique=True, verbose_name="placa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("COMPLETO", "Completo")],
                        default="RASCUNHO",
                        editable=False,
                        max_length=20,
                        verbose_name="situação do cadastro",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CARACTERIZADA", "Caracterizada"),
                            ("DESCARACTERIZADA", "Descaracterizada"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "combustivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viaturas",
                        to="viagens_cadastros.combustivel",
                        verbose_name="combustível",
                    ),
                ),
                (
                    "motoristas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viaturas_que_dirige",
                        to="viagens_cadastros.servidor",
                        verbose_name="motoristas",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viaturas",
                        to="viagens_cadastros.unidade",
                        verbose_name="unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "viatura",
                "verbose_name_plural": "viaturas",
                "ordering": ["placa"],
            },
        ),
        migrations.AddConstraint(
            model_name="servidor",
            constraint=models.UniqueConstraint(
                fields=("nome",), name="viagens_servidor_nome_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="servidor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("cpf",),
                name="viagens_servidor_cpf_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="servidor",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("rg", ""), _negated=True),
                    models.Q(("rg", "NAO POSSUI RG"), _negated=True),
                ),
                fields=("rg",),
                name="viagens_servidor_rg_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="servidor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telefone", ""), _negated=True),
                fields=("telefone",),
                name="viagens_servidor_telefone_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="servidor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legado_pk__isnull", False)),
                fields=("legado_origem", "legado_pk"),
                name="viagens_servidor_legado_unico",
            ),
        ),
    ]
