# Generated by Django 5.2.16 on 2026-09-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_cadastros', '0002_seed_modulo_viagens'),
        # A conversão histórica de motoristas ainda lê `Servidor.ativo`.
        ('solicitacoes', '0019_motorista_aponta_para_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='combustivel',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='ativo',
        ),
    ]
