# Generated by Django 6.1 on 2026-09-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_municipio_coordenadas'),
        ('viagens_cadastros', '0003_remove_cargo_ativo_remove_combustivel_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('prazo_justificativa_dias', models.PositiveIntegerField(default=10)),
                ('nome_orgao', models.CharField(blank=True, max_length=200)),
                ('sigla_orgao', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('logradouro', models.CharField(blank=True, default='', max_length=160)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cidade_endereco', models.CharField(blank=True, default='', max_length=120)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('ramal', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sede', models.CharField(blank=True, default='', max_length=200)),
                ('nome_chefia', models.CharField(blank=True, default='', max_length=120)),
                ('cargo_chefia', models.CharField(blank=True, default='', max_length=120)),
                ('destinatario_oficio_nome', models.CharField(blank=True, default='', max_length=255)),
                ('destinatario_oficio_cargo', models.CharField(blank=True, default='', max_length=120)),
                ('destinatario_oficio_unidade', models.CharField(blank=True, default='', max_length=255)),
                ('chave', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('cidade_sede_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.municipio', verbose_name='Cidade sede padrão')),
                ('destinatario_oficio', models.ForeignKey(blank=True, help_text='A unidade lotada deste servidor vira o DESTINO do cabeçalho do Ofício.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Destinatário padrão do Ofício')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'configuração institucional de viagens',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('OFICIO', 'Ofício'), ('JUSTIFICATIVA', 'Justificativa')], max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Servidor')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='viagens_cadastros.configuracaosistema')),
            ],
            options={
                'ordering': ['tipo', 'ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracaosistema',
            constraint=models.CheckConstraint(condition=models.Q(('chave', 1)), name='viagens_config_singleton'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaconfiguracao',
            constraint=models.UniqueConstraint(fields=('configuracao', 'tipo', 'ordem'), name='viagens_assinatura_ordem_unica'),
        ),
    ]
