# Generated by Django 6.1 on 2026-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('viagens_cadastros', '0004_configuracaosistema_assinaturaconfiguracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturaconfiguracao',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='assinaturaconfiguracao',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='combustivel',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='combustivel',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='tabeladiaria',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='tabeladiaria',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='legado_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem no legado'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='legado_pk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id no legado'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaconfiguracao',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_assinaturaconfiguracao_origem'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_cargo_origem'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_combustivel_origem'),
        ),
        migrations.AddConstraint(
            model_name='configuracaosistema',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_configuracaosistema_origem'),
        ),
        migrations.AddConstraint(
            model_name='tabeladiaria',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_tabeladiaria_origem'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_unidade_origem'),
        ),
        migrations.AddConstraint(
            model_name='viatura',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_viatura_origem'),
        ),
    ]
