# Generated by Django 6.1 on 2026-09-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_origem_legado'),
        ('cadastros', '0010_origem_legado'),
        ('viagens_cadastros', '0005_origem_legado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuracaosistema',
            name='viagens_config_singleton',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='setor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_viagens', to='accounts.setor', verbose_name='setor'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='chave',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddConstraint(
            model_name='configuracaosistema',
            constraint=models.UniqueConstraint(condition=models.Q(('setor__isnull', True)), fields=('chave',), name='viagens_config_global_unica'),
        ),
    ]
