# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens_cadastros', '0006_configuracao_por_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='coordenador_adm_plano_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens_cadastros.servidor', verbose_name='Coordenador administrativo padrão (Plano de Trabalho)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_ano',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_sufixo_numero',
            field=models.CharField(blank=True, default='ASCOM', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='pt_ultimo_numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assinaturaconfiguracao',
            name='tipo',
            field=models.CharField(choices=[('OFICIO', 'Ofício'), ('JUSTIFICATIVA', 'Justificativa'), ('ORDEM_SERVICO', 'Ordem de Serviço'), ('PLANO_TRABALHO', 'Plano de Trabalho')], max_length=30),
        ),
    ]
