# Generated by Django 6.1.1 on 2026-09-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "viagens_cadastros",
            "0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaSubstituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "legado_origem",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="origem no legado"
                    ),
                ),
                (
                    "legado_pk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="id no legado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos os documentos"),
                            ("OFICIO", "Ofício"),
                            ("JUSTIFICATIVA", "Justificativa"),
                            ("ORDEM_SERVICO", "Ordem de Serviço"),
                            ("PLANO_TRABALHO", "Plano de Trabalho"),
                        ],
                        default="TODOS",
                        max_length=30,
                        verbose_name="Documentos",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="Início")),
                (
                    "fim",
                    models.DateField(
                        blank=True,
                        help_text="Vazio: até ser encerrada.",
                        null=True,
                        verbose_name="Fim",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex.: férias do titular.",
                        max_length=120,
                        verbose_name="Motivo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "configuracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substituicoes_assinatura",
                        to="viagens_cadastros.configuracaosistema",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="viagens_cadastros.servidor",
                        verbose_name="Substituto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Substituição de assinante",
                "verbose_name_plural": "Substituições de assinante",
                "ordering": ["-inicio", "tipo"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("legado_pk__isnull", False)),
                        fields=("legado_origem", "legado_pk"),
                        name="f6_assinaturasubstituicao_origem",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fim__isnull", True),
                            ("fim__gte", models.F("inicio")),
                            _connector="OR",
                        ),
                        name="viagens_substituicao_periodo_ordenado",
                    ),
                ],
            },
        ),
    ]
