# Generated by Django 6.1.1 on 2026-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "viagens_cadastros",
            "0007_configuracaosistema_coordenador_adm_plano_trabalho_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="setor_despacho_eprotocolo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome do setor, como aparece no eProtocolo. Quando o processo chega nele, a equipe é avisada.",
                max_length=160,
                verbose_name="Setor do despacho no eProtocolo",
            ),
        ),
    ]
