# Generated by Django 6.1.1 on 2026-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_cadastros", "0008_assinante_substituto"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="ascom_cabecalho_unidade",
            field=models.CharField(
                blank=True,
                default="ASSESSORIA DE COMUNICAÇÃO SOCIAL",
                max_length=160,
                verbose_name="Unidade no cabeçalho (Coffee Break)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="ascom_rodape_contato",
            field=models.CharField(
                blank=True,
                default="Fone: (41) 3235-6477 – e-mail:  comunicacao@pc.pr.gov.br",
                max_length=255,
                verbose_name="Contato no rodapé (Coffee Break)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="ascom_rodape_endereco",
            field=models.CharField(
                blank=True,
                default="Avenida Iguaçu, 470 – Rebouças – Curitiba/PR—CEP: 80.230-020",
                max_length=255,
                verbose_name="Endereço no rodapé (Coffee Break)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosistema",
            name="delegado_geral_nome",
            field=models.CharField(
                blank=True,
                default="Silvio Jacob Rockembach",
                max_length=120,
                verbose_name="Delegado-Geral",
            ),
        ),
    ]
