# Generated by Django 6.1 on 2026-09-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'responsável da equipe',
                'verbose_name_plural': 'responsáveis da equipe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'unidade responsável',
                'verbose_name_plural': 'unidades responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da pauta')),
                ('fonte', models.CharField(blank=True, help_text='Quem passou a informação (delegado, investigador, assessoria).', max_length=200, verbose_name='fonte da pauta')),
                ('inicio_pauta', models.TimeField(blank=True, null=True, verbose_name='início da pauta')),
                ('titulo', models.CharField(max_length=300, verbose_name='título da pauta')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('PUBLICADA', 'Publicada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15, verbose_name='status')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('colocada_edicao', models.TimeField(blank=True, null=True, verbose_name='colocada para edição')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('horario_publicacao', models.TimeField(blank=True, null=True, verbose_name='horário de publicação')),
                ('bitly_grupos', models.BooleanField(blank=True, null=True, verbose_name='Bitly nos grupos')),
                ('enviado_sesp', models.BooleanField(blank=True, null=True, verbose_name='enviado para a SESP')),
                ('publicado_aen', models.BooleanField(blank=True, null=True, verbose_name='publicado na AEN')),
                ('link_site', models.URLField(blank=True, max_length=500, verbose_name='link no site da PCPR')),
                ('link_aen', models.URLField(blank=True, max_length=500, verbose_name='link na AEN')),
                ('chave_importacao', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='chave da importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('galeria_fotos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pautas_galeria', to='publicacoes.responsavel', verbose_name='galeria de fotos')),
                ('jornalista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pautas', to='publicacoes.responsavel', verbose_name='jornalista responsável')),
                ('revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pautas_revisadas', to='publicacoes.responsavel', verbose_name='revisão')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pautas', to='publicacoes.unidade', verbose_name='unidade responsável')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-data', '-inicio_pauta', '-pk'],
                'indexes': [models.Index(fields=['status', 'data'], name='publicacao_status_data_idx'), models.Index(fields=['data_publicacao'], name='publicacao_data_pub_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_publicacao__isnull', True), ('data_publicacao__gte', models.F('data')), _connector='OR'), name='publicacao_publicada_apos_pauta')],
            },
        ),
    ]
