# Generated by Django 6.1 on 2026-09-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'responsável da equipe',
                'verbose_name_plural': 'responsáveis da equipe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'veículo de imprensa',
                'verbose_name_plural': 'veículos de imprensa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do pedido')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='horário do pedido')),
                ('jornalista', models.CharField(max_length=150, verbose_name='jornalista')),
                ('contato', models.CharField(blank=True, max_length=150, verbose_name='contato')),
                ('pedido', models.TextField(verbose_name='pedido')),
                ('situacao', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('EM_ANDAMENTO_TEXTO', 'Em andamento — texto'), ('EM_ANDAMENTO_VIDEO', 'Em andamento — vídeo'), ('AGUARDANDO_FONTE', 'Aguardando fonte'), ('AGUARDANDO_PRODUTORA', 'Aguardando produtora'), ('AGUARDAR_NOVA_SOLICITACAO', 'Aguardar nova solicitação'), ('PROXIMO_MES', 'Próximo mês'), ('ATENDIDO', 'Atendido'), ('NAO_RESPONDER', 'Não responder')], default='EM_ANDAMENTO', max_length=30, verbose_name='situação')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline / veiculação')),
                ('horario_resposta', models.TimeField(blank=True, null=True, verbose_name='horário da resposta')),
                ('fonte', models.TextField(blank=True, help_text='Uma fonte por linha (delegado, assessoria, unidade).', verbose_name='fontes consultadas')),
                ('inicio_pedido', models.TextField(blank=True, help_text='Horário em que cada fonte foi acionada, uma por linha.', verbose_name='início do pedido às fontes')),
                ('final_pedido', models.TextField(blank=True, help_text='Horário em que cada fonte respondeu, uma por linha.', verbose_name='retorno das fontes')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta enviada')),
                ('chave_importacao', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='chave da importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_imprensa_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimento_imprensa.responsavel', verbose_name='responsável pelo atendimento')),
                ('responsavel_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_respondidos', to='atendimento_imprensa.responsavel', verbose_name='responsável pela resposta')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimento_imprensa.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'atendimento à imprensa',
                'verbose_name_plural': 'atendimentos à imprensa',
                'ordering': ['-data', '-horario', '-pk'],
                'indexes': [models.Index(fields=['situacao', 'data'], name='atend_situacao_data_idx'), models.Index(fields=['deadline'], name='atend_deadline_idx')],
            },
        ),
    ]
