# Generated by Django 6.1 on 2026-09-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_imprensa', '0002_seed_modulo_ascom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ativo',
        ),
        migrations.CreateModel(
            name='HistoricoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Registro criado'), ('ATUALIZACAO', 'Registro atualizado'), ('TRANSICAO', 'Situação alterada')], max_length=20, verbose_name='ação')),
                ('status_anterior', models.CharField(blank=True, max_length=30, verbose_name='situação anterior')),
                ('status_novo', models.CharField(blank=True, max_length=30, verbose_name='situação nova')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='atendimento_imprensa.atendimento', verbose_name='atendimento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_atendimentos_imprensa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'histórico de atendimentos à imprensa',
                'verbose_name_plural': 'históricos de atendimentos à imprensa',
                'ordering': ['criado_em', 'pk'],
            },
        ),
    ]
