# Generated by Django 6.1 on 2026-08-31 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_normaliza_nomes_em_caixa_alta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, unique=True, verbose_name='razão social')),
                ('cnpj', models.CharField(blank=True, help_text='Somente números; normalizado automaticamente.', max_length=14, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=150, verbose_name='contato')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'fornecedor de coffee break',
                'verbose_name_plural': 'fornecedores de coffee break',
                'ordering': ['razao_social'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='cnpj_unico_fornecedor')],
            },
        ),
        migrations.CreateModel(
            name='ContratoCoffeeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='número do contrato')),
                ('numero_gms', models.CharField(blank=True, max_length=30, verbose_name='número GMS')),
                ('termo_aditivo', models.CharField(blank=True, max_length=50, verbose_name='termo aditivo')),
                ('fiscal_responsavel', models.CharField(blank=True, help_text='Fiscal que atesta as notas fiscais.', max_length=150, verbose_name='fiscal responsável')),
                ('objeto', models.CharField(blank=True, max_length=255, verbose_name='objeto')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='coffee_break.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'contrato de coffee break',
                'verbose_name_plural': 'contratos de coffee break',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='LoteCoffeeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='número do lote')),
                ('exercicio', models.CharField(help_text='Vigência do quantitativo (ex.: 2026).', max_length=9, verbose_name='exercício')),
                ('quantidade_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade total contratada')),
                ('empenho', models.CharField(blank=True, max_length=30, verbose_name='empenho')),
                ('municipios_texto', models.TextField(blank=True, help_text='Lista original da planilha, preservada integralmente.', verbose_name='municípios (texto original)')),
                ('orientacoes', models.TextField(blank=True, verbose_name='orientações')),
                ('especificacoes_tecnicas', models.TextField(blank=True, verbose_name='especificações técnicas')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='coffee_break.contratocoffeebreak', verbose_name='contrato')),
                ('municipios', models.ManyToManyField(blank=True, related_name='lotes_coffee_break', to='cadastros.municipio', verbose_name='municípios abrangidos')),
            ],
            options={
                'verbose_name': 'lote de coffee break',
                'verbose_name_plural': 'lotes de coffee break',
                'ordering': ['-exercicio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCoffeeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da solicitação')),
                ('data_inicio_evento', models.DateField(blank=True, null=True, verbose_name='data de início do evento')),
                ('data_fim_evento', models.DateField(blank=True, null=True, verbose_name='data de fim do evento')),
                ('periodo_evento_texto', models.CharField(blank=True, help_text='Períodos irregulares da planilha (ex.: "23, 24 e 25/03").', max_length=120, verbose_name='período do evento (texto original)')),
                ('numero', models.CharField(blank=True, help_text='Identificador institucional — sempre texto (ex.: 02/2026).', max_length=20, verbose_name='número da solicitação')),
                ('descricao_evento', models.TextField(verbose_name='descrição do evento')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade solicitada')),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=30, verbose_name='número da nota fiscal')),
                ('protocolo_pagamento', models.CharField(blank=True, max_length=30, verbose_name='protocolo de pagamento')),
                ('data_atesto_gaf', models.DateField(blank=True, null=True, verbose_name='data de atesto e envio ao GAF')),
                ('data_ordem_bancaria', models.DateField(blank=True, null=True, verbose_name='ordem bancária emitida em')),
                ('data_envio_empresa', models.DateField(blank=True, null=True, verbose_name='ordem bancária enviada à empresa em')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cancelada', models.BooleanField(default=False, verbose_name='cancelada')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, verbose_name='motivo do cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_coffee_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_coffee_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='coffee_break.lotecoffeebreak', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'solicitação de coffee break',
                'verbose_name_plural': 'solicitações de coffee break',
                'ordering': ['-data_solicitacao', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotecoffeebreak',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero', 'exercicio'), name='lote_unico_por_contrato_e_exercicio'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaocoffeebreak',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_evento__isnull', True), ('data_fim_evento__isnull', True), ('data_fim_evento__gte', models.F('data_inicio_evento')), _connector='OR'), name='coffee_periodo_evento_valido'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaocoffeebreak',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1), ('cancelada', True), _connector='OR'), name='coffee_quantidade_positiva'),
        ),
    ]
