# Generated by Django 6.1 on 2026-09-01 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_break', '0002_seed_modulo_ascom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCoffeeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Solicitação criada'), ('ATUALIZACAO', 'Solicitação atualizada'), ('CANCELAMENTO', 'Solicitação cancelada'), ('REATIVACAO', 'Solicitação reativada')], max_length=20, verbose_name='ação')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'histórico de coffee break',
                'verbose_name_plural': 'históricos de coffee break',
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitacaocoffeebreak',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('lote', 'numero'), name='coffee_numero_unico_por_lote'),
        ),
        migrations.AddField(
            model_name='historicocoffeebreak',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='coffee_break.solicitacaocoffeebreak', verbose_name='solicitação'),
        ),
        migrations.AddField(
            model_name='historicocoffeebreak',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_coffee_break', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
