# Generated by Django 6.1 on 2026-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_break', '0003_auditoria_integridade_financeira'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solicitacaocoffeebreak',
            constraint=models.CheckConstraint(condition=models.Q(('data_ordem_bancaria__isnull', True), ('data_atesto_gaf__isnull', True), ('data_ordem_bancaria__gte', models.F('data_atesto_gaf')), _connector='OR'), name='coffee_ob_apos_atesto'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaocoffeebreak',
            constraint=models.CheckConstraint(condition=models.Q(('data_envio_empresa__isnull', True), ('data_ordem_bancaria__isnull', True), ('data_envio_empresa__gte', models.F('data_ordem_bancaria')), _connector='OR'), name='coffee_envio_apos_ob'),
        ),
    ]
