# Generated by Django 6.1 on 2026-09-21 20:11

import coffee_break.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Portal municipal de cada fornecedor conhecido (sede): Curitiba e Cascavel.
PORTAIS_MUNICIPAIS = {
    "35014719000166": "https://cnd-cidadao.curitiba.pr.gov.br/Certidao/SolicitarCnpj",
    "45549407000100": "https://prefa.cascavel.pr.gov.br/autoatendimento/servicos/certidao-negativa-de-debitos/detalhar/1",
}


def preencher_portais(apps, schema_editor):
    Fornecedor = apps.get_model("coffee_break", "Fornecedor")
    for cnpj, url in PORTAIS_MUNICIPAIS.items():
        Fornecedor.objects.filter(cnpj=cnpj, url_certidao_municipal="").update(
            url_certidao_municipal=url
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_origem_legado'),
        ('coffee_break', '0004_constraints_fluxo_financeiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocoffeebreak',
            name='arquivo_contrato',
            field=models.FileField(blank=True, help_text='Vai no pacote do protocolo de pagamento.', upload_to='coffee_break/contratos/', verbose_name='contrato (PDF)'),
        ),
        migrations.AddField(
            model_name='contratocoffeebreak',
            name='arquivo_termo_aditivo',
            field=models.FileField(blank=True, help_text='Se houver; vai no pacote logo depois do contrato.', upload_to='coffee_break/contratos/', verbose_name='termo aditivo (PDF)'),
        ),
        migrations.AddField(
            model_name='contratocoffeebreak',
            name='cargo_fiscal',
            field=models.CharField(blank=True, default='Agente de Polícia Judiciária', max_length=100, verbose_name='cargo do fiscal'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='url_certidao_municipal',
            field=models.URLField(blank=True, help_text='Portal da prefeitura da sede do fornecedor (as demais certidões têm portal único).', max_length=300, verbose_name='portal da certidão municipal'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='arquivo_nota_fiscal',
            field=models.FileField(blank=True, upload_to='coffee_break/notas/%Y/', verbose_name='nota fiscal (PDF)'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='data_envio_ordem_servico',
            field=models.DateField(blank=True, null=True, verbose_name='OS enviada ao fornecedor em'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='detalhamento_pedido',
            field=models.TextField(blank=True, help_text='Em branco, a OS monta o texto com as datas, o horário e a quantidade.', verbose_name='detalhamento do pedido'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='horario_evento',
            field=models.TimeField(blank=True, null=True, verbose_name='horário'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='local_entrega',
            field=models.CharField(blank=True, max_length=255, verbose_name='local de entrega'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='O lote é escolhido pelo município.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coffee_breaks', to='cadastros.municipio', verbose_name='município do evento'),
        ),
        migrations.AddField(
            model_name='solicitacaocoffeebreak',
            name='responsavel_recebimento',
            field=models.CharField(blank=True, help_text='Nome e telefone de quem recebe no local.', max_length=150, verbose_name='responsável pelo recebimento'),
        ),
        migrations.CreateModel(
            name='CertidaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual (Paraná)'), ('MUNICIPAL', 'Municipal'), ('TRABALHISTA', 'Trabalhista'), ('FGTS', 'FGTS')], max_length=12, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to=coffee_break.models._certidao_upload_to, verbose_name='certidão (PDF)')),
                ('validade', models.DateField(verbose_name='válida até')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certidoes_coffee_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certidoes', to='coffee_break.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'certidão de fornecedor',
                'verbose_name_plural': 'certidões de fornecedores',
                'ordering': ['fornecedor', 'tipo', '-validade', '-criado_em'],
            },
        ),
        migrations.RunPython(preencher_portais, migrations.RunPython.noop),
    ]
