# Generated by Django 6.1 on 2026-09-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_break', '0005_ordem_servico_certidoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocoffeebreak',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='lotecoffeebreak',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Só lotes vigentes recebem solicitações pelo município.', verbose_name='lote vigente'),
        ),
    ]
