# Generated by Django 6.1.1 on 2026-09-22 20:49

from django.db import migrations, models


def criar_configuracao(apps, schema_editor):
    apps.get_model("coffee_break", "ConfiguracaoCoffeeBreak").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0006_fornecedor_e_contrato_sem_ativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoCoffeeBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oficio_vocativo",
                    models.CharField(
                        default="Excelentíssimo Senhor Delegado:",
                        max_length=120,
                        verbose_name="vocativo do ofício",
                    ),
                ),
                (
                    "oficio_assinante",
                    models.CharField(
                        default="JOÃO MÁRIO NUNES DE GOES",
                        max_length=150,
                        verbose_name="quem assina o ofício",
                    ),
                ),
                (
                    "oficio_cargo_assinante",
                    models.CharField(
                        default="Assessor de Comunicação Social",
                        max_length=150,
                        verbose_name="cargo de quem assina",
                    ),
                ),
                (
                    "oficio_destinatario",
                    models.TextField(
                        default="Exm° Sr. Delegado\nDr. Marcos Maurício Pestano\nGrupo Auxiliar Financeiro - GAF\nDepartamento da Polícia Civil\nCuritiba/PR",
                        help_text="Uma linha por linha do bloco no pé do ofício.",
                        verbose_name="destinatário do ofício",
                    ),
                ),
                (
                    "eprotocolo_assunto",
                    models.CharField(
                        default="LICITACAO",
                        max_length=80,
                        verbose_name="assunto no eProtocolo",
                    ),
                ),
                (
                    "eprotocolo_palavras_chave",
                    models.CharField(
                        default="REGISTRO DE PRECO",
                        max_length=120,
                        verbose_name="palavras-chave no eProtocolo",
                    ),
                ),
                (
                    "despacho_destino",
                    models.CharField(
                        default="Ao GAF,",
                        max_length=80,
                        verbose_name="despacho: a quem vai",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "ofício e eProtocolo",
                "verbose_name_plural": "ofício e eProtocolo",
            },
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="clausula_pagamento",
            field=models.CharField(
                blank=True,
                default="Cláusula Décima, item 10.2.6",
                help_text="Citada no ofício que encaminha a nota para pagamento.",
                max_length=120,
                verbose_name="cláusula do pagamento",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="nome_curto",
            field=models.CharField(
                blank=True,
                help_text="Como aparece no detalhamento do eProtocolo, ex.: FAVO E MEL.",
                max_length=60,
                verbose_name="nome curto",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="data_oficio",
            field=models.DateField(
                blank=True, null=True, verbose_name="data do ofício"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="numero_oficio",
            field=models.CharField(
                blank=True,
                help_text="O ofício que encaminha a nota ao GAF (ex.: 124/2026).",
                max_length=20,
                verbose_name="número do ofício",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="protocolo_pcpr_oficio",
            field=models.CharField(
                blank=True,
                help_text="Número que vai no alto do ofício (ex.: 2026.050880.000).",
                max_length=40,
                verbose_name="PCPR protocolo n.º",
            ),
        ),
        migrations.RunPython(criar_configuracao, migrations.RunPython.noop),
    ]
