# Generated by Django 6.1.1 on 2026-09-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0007_oficio_e_eprotocolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="quantidade_contratada",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="quantidade contratada"
            ),
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="valor total",
            ),
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="valor unitário",
            ),
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="vigencia_estimada",
            field=models.BooleanField(default=False, verbose_name="vigência estimada"),
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="vigencia_fim",
            field=models.DateField(
                blank=True,
                help_text="Lida do termo aditivo; do contrato inicial, estimada pelo prazo.",
                null=True,
                verbose_name="vigência — fim",
            ),
        ),
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="vigencia_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="vigência — início"
            ),
        ),
    ]
