# Generated by Django 6.1.1 on 2026-09-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0008_contrato_lido_do_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="pagamento_com",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamento_junto",
                to="coffee_break.solicitacaocoffeebreak",
                verbose_name="pagamento junto com",
            ),
        ),
    ]
