# Generated by Django 6.1.1 on 2026-09-24 02:01

import django.db.models.deletion
from django.db import migrations, models


def trazer_aditivos(apps, schema_editor):
    """O aditivo que o contrato já tinha vira o primeiro da lista."""
    Contrato = apps.get_model("coffee_break", "ContratoCoffeeBreak")
    Aditivo = apps.get_model("coffee_break", "AditivoContrato")
    for contrato in Contrato.objects.exclude(termo_aditivo=""):
        Aditivo.objects.get_or_create(
            contrato=contrato,
            numero=contrato.termo_aditivo,
            defaults={
                "arquivo": contrato.arquivo_termo_aditivo.name if contrato.arquivo_termo_aditivo else "",
                "vigencia_inicio": None if contrato.vigencia_estimada else contrato.vigencia_inicio,
                "vigencia_fim": None if contrato.vigencia_estimada else contrato.vigencia_fim,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0009_pagamento_conjunto"),
    ]

    operations = [
        migrations.CreateModel(
            name="AditivoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50, verbose_name="número do termo aditivo"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        upload_to="coffee_break/contratos/",
                        verbose_name="termo aditivo (PDF)",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência — início"
                    ),
                ),
                (
                    "vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência — fim"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aditivos",
                        to="coffee_break.contratocoffeebreak",
                        verbose_name="contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "termo aditivo",
                "verbose_name_plural": "termos aditivos",
                "ordering": ["vigencia_inicio", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contrato", "numero"),
                        name="coffee_aditivo_unico_por_contrato",
                    )
                ],
            },
        ),
        migrations.RunPython(trazer_aditivos, migrations.RunPython.noop),
    ]
