# Generated by Django 6.1.1 on 2026-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0010_aditivos_do_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratocoffeebreak",
            name="antecedencia_minima_dias",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Pedido com menos dias até o evento aparece com aviso para ligar ao fornecedor.",
                verbose_name="antecedência mínima do pedido (dias)",
            ),
        ),
    ]
