# Generated by Django 6.1.1 on 2026-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0011_antecedencia_minima"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="em_correcao",
            field=models.BooleanField(
                default=False, verbose_name="reaberta para correção"
            ),
        ),
    ]
