# Generated by Django 6.1.1 on 2026-09-26 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0012_reabrir_para_correcao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="quantidade_faturada",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A da nota fiscal. Em branco, o lote desconta a quantidade pedida.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="quantidade faturada",
            ),
        ),
    ]
