# Generated by Django 6.1.1 on 2026-09-26 03:57

from django.db import migrations, models


def copiar_preco_do_contrato(apps, schema_editor):
    """As OS que já existem guardam o preço atual do contrato: um reajuste
    daqui para a frente não muda o valor delas."""
    Solicitacao = apps.get_model("coffee_break", "SolicitacaoCoffeeBreak")
    for s in Solicitacao.objects.filter(valor_unitario__isnull=True, lote__contrato__valor_unitario__isnull=False).select_related("lote__contrato"):
        Solicitacao.objects.filter(pk=s.pk).update(valor_unitario=s.lote.contrato.valor_unitario)


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0013_quantidade_faturada"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotecoffeebreak",
            name="valor_empenho",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quanto foi empenhado para o lote: o painel mostra o comprometido e o pago contra ele.",
                max_digits=14,
                null=True,
                verbose_name="valor do empenho",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Cópia do preço do contrato na data do pedido: reajuste depois não muda o valor da OS.",
                max_digits=12,
                null=True,
                verbose_name="valor unitário",
            ),
        ),
        migrations.RunPython(copiar_preco_do_contrato, migrations.RunPython.noop),
    ]
