# Generated by Django 6.1.1 on 2026-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0014_controle_em_reais"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="cnpj_emitente_nf",
            field=models.CharField(
                blank=True, max_length=14, verbose_name="CNPJ do emitente da nota"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="data_emissao_nf",
            field=models.DateField(
                blank=True, null=True, verbose_name="emissão da nota fiscal"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="valor_nota_fiscal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="valor da nota fiscal",
            ),
        ),
    ]
