# Generated by Django 6.1.1 on 2026-09-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0015_conferencia_da_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocoffeebreak",
            name="email_copia",
            field=models.CharField(
                blank=True,
                help_text="Vai em cópia nos e-mails ao fornecedor. Mais de um: separe por vírgula.",
                max_length=300,
                verbose_name="e-mail da ASCOM em cópia",
            ),
        ),
        migrations.AddField(
            model_name="configuracaocoffeebreak",
            name="email_os_assunto",
            field=models.CharField(
                default="Ordem de Serviço {numero} – Coffee Break – {evento}",
                help_text="Pode usar {numero}, {evento}, {data}, {horario}, {local}, {responsavel}, {quantidade} e {fornecedor}.",
                max_length=200,
                verbose_name="assunto do e-mail da OS",
            ),
        ),
        migrations.AddField(
            model_name="configuracaocoffeebreak",
            name="email_os_texto",
            field=models.TextField(
                default='Prezados,\n\nSegue em anexo a Ordem de Serviço {numero}, referente ao coffee break para {quantidade} pessoas no evento "{evento}".\n\nData: {data}\nHorário: {horario}\nLocal de entrega: {local}\nResponsável pelo recebimento: {responsavel}\n\nPor favor, confirmem o recebimento desta mensagem.\n\nAtenciosamente,\nAssessoria de Comunicação Social – PCPR',
                help_text="Os mesmos campos do assunto, entre chaves.",
                verbose_name="texto do e-mail da OS",
            ),
        ),
        migrations.AlterField(
            model_name="historicocoffeebreak",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Solicitação criada"),
                    ("ATUALIZACAO", "Solicitação atualizada"),
                    ("CANCELAMENTO", "Solicitação cancelada"),
                    ("REATIVACAO", "Solicitação reativada"),
                    ("EMAIL", "E-mail enviado"),
                ],
                max_length=20,
                verbose_name="ação",
            ),
        ),
    ]
