# Generated by Django 6.1.1 on 2026-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0016_email_ao_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocoffeebreak",
            name="email_ob_assunto",
            field=models.CharField(
                default="Ordem bancária {ordem_bancaria} – pagamento da nota fiscal {nota} – Coffee Break",
                help_text="Além dos campos da OS: {nota}, {ordem_bancaria} e {data_ordem_bancaria}.",
                max_length=200,
                verbose_name="assunto do e-mail da ordem bancária",
            ),
        ),
        migrations.AddField(
            model_name="configuracaocoffeebreak",
            name="email_ob_texto",
            field=models.TextField(
                default='Prezados,\n\nInformamos que foi emitida a ordem bancária {ordem_bancaria}, de {data_ordem_bancaria}, referente ao pagamento da nota fiscal {nota} (coffee break do evento "{evento}"). Segue o comprovante em anexo.\n\nAtenciosamente,\nAssessoria de Comunicação Social – PCPR',
                verbose_name="texto do e-mail da ordem bancária",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="arquivo_ordem_bancaria",
            field=models.FileField(
                blank=True,
                upload_to="coffee_break/ordens_bancarias/%Y/",
                verbose_name="ordem bancária (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="numero_ordem_bancaria",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="número da ordem bancária"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="valor_ordem_bancaria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="valor da ordem bancária",
            ),
        ),
    ]
