# Generated by Django 6.1.1 on 2026-09-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0017_ordem_bancaria_anexada"),
        ("demandas_eventos", "0014_encaminhar_a_dg"),
        ("solicitacoes", "0021_protocolo_eprotocolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="demanda_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coffee_breaks",
                to="demandas_eventos.demandaevento",
                verbose_name="palestra ou evento da ASCOM",
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="solicitacao_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coffee_breaks",
                to="solicitacoes.solicitacaoevento",
                verbose_name="solicitação de evento",
            ),
        ),
    ]
