# Generated by Django 6.1.1 on 2026-09-26 04:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0018_origem_do_pedido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTREGUE", "Entregue sem ocorrência"),
                            ("ATRASO", "Atraso na entrega"),
                            ("FALTA", "Falta de itens"),
                            ("QUALIDADE", "Problema de qualidade"),
                            ("NAO_ENTREGUE", "Não entregue"),
                            ("OUTRO", "Outra ocorrência"),
                        ],
                        default="ENTREGUE",
                        max_length=15,
                        verbose_name="o que aconteceu",
                    ),
                ),
                (
                    "avaliacao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="avaliação (1 a 5)",
                    ),
                ),
                (
                    "recebido_por",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="quem recebeu"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="observação")),
                (
                    "foto",
                    models.FileField(
                        blank=True,
                        help_text="Opcional: PDF, PNG ou JPG.",
                        upload_to="coffee_break/ocorrencias/%Y/",
                        verbose_name="foto ou documento",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrada em"
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_coffee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrada por",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="coffee_break.solicitacaocoffeebreak",
                        verbose_name="solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrega e ocorrência",
                "verbose_name_plural": "entregas e ocorrências",
                "ordering": ["-criado_em", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("avaliacao__isnull", True),
                            models.Q(("avaliacao__gte", 1), ("avaliacao__lte", 5)),
                            _connector="OR",
                        ),
                        name="coffee_avaliacao_1_a_5",
                    )
                ],
            },
        ),
    ]
