# Generated by Django 6.1.1 on 2026-09-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0019_entregas_e_ocorrencias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicocoffeebreak",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Solicitação criada"),
                    ("ATUALIZACAO", "Solicitação atualizada"),
                    ("CANCELAMENTO", "Solicitação cancelada"),
                    ("REATIVACAO", "Solicitação reativada"),
                    ("EMAIL", "E-mail enviado"),
                    ("FORNECEDOR", "Envio do fornecedor"),
                ],
                max_length=20,
                verbose_name="ação",
            ),
        ),
        migrations.CreateModel(
            name="LinkFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="hash do token",
                    ),
                ),
                ("expira_em", models.DateTimeField(verbose_name="vale até")),
                (
                    "revogado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revogado em"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links_fornecedor_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "revogado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links_fornecedor_revogados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revogado por",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_fornecedor",
                        to="coffee_break.solicitacaocoffeebreak",
                        verbose_name="solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "link do fornecedor",
                "verbose_name_plural": "links do fornecedor",
                "ordering": ["-criado_em", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="EnvioFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NOTA", "Nota fiscal"),
                            ("FEDERAL", "Certidão Federal"),
                            ("ESTADUAL", "Certidão Estadual (Paraná)"),
                            ("MUNICIPAL", "Certidão Municipal"),
                            ("TRABALHISTA", "Certidão Trabalhista"),
                            ("FGTS", "Certidão FGTS"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="coffee_break/envios_fornecedor/%Y/",
                        verbose_name="arquivo",
                    ),
                ),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="número da nota"
                    ),
                ),
                (
                    "valor_nota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor da nota",
                    ),
                ),
                (
                    "emissao_nota",
                    models.DateField(
                        blank=True, null=True, verbose_name="emissão da nota"
                    ),
                ),
                (
                    "cnpj_nota",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CNPJ do emitente"
                    ),
                ),
                (
                    "validade_certidao",
                    models.DateField(
                        blank=True, null=True, verbose_name="certidão válida até"
                    ),
                ),
                (
                    "avisos",
                    models.TextField(blank=True, verbose_name="pontos a conferir"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEBIDO", "Recebido, aguardando conferência"),
                            ("ACEITO", "Conferido e aceito"),
                            ("RECUSADO", "Recusado"),
                        ],
                        default="RECEBIDO",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "conferido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="conferido em"
                    ),
                ),
                (
                    "motivo_recusa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo da recusa"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebido em"),
                ),
                (
                    "conferido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_fornecedor_conferidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="conferido por",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="coffee_break.linkfornecedor",
                        verbose_name="link",
                    ),
                ),
            ],
            options={
                "verbose_name": "envio do fornecedor",
                "verbose_name_plural": "envios do fornecedor",
                "ordering": ["-criado_em", "-pk"],
            },
        ),
    ]
