# Generated by Django 6.1.1 on 2026-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_break", "0020_link_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="bairro",
            field=models.CharField(blank=True, max_length=120, verbose_name="bairro"),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="cep",
            field=models.CharField(
                blank=True, help_text="00000-000", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaocoffeebreak",
            name="endereco",
            field=models.CharField(
                blank=True,
                help_text="Logradouro, número e complemento.",
                max_length=255,
                verbose_name="endereço",
            ),
        ),
    ]
