# Generated by Django 5.2.16 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viagens_planos', '0001_initial'),
        ('viagens_viagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_trabalho', to='viagens_viagem.viagem', verbose_name='Viagem'),
        ),
        migrations.AddField(
            model_name='planodestino',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens_planos.planotrabalho'),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='viagens_planos.planotrabalho'),
        ),
        migrations.AddField(
            model_name='efetivoplano',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivos', to='viagens_planos.planotrabalho'),
        ),
        migrations.AddField(
            model_name='presetatividadesplanotrabalho',
            name='atividades',
            field=models.ManyToManyField(blank=True, related_name='presets', to='viagens_planos.atividadeplanotrabalho', verbose_name='Atividades'),
        ),
        migrations.AddConstraint(
            model_name='programasolicitante',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_programasolicitante_origem'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='viagens_planos.programasolicitante', verbose_name='Programa solicitante'),
        ),
        migrations.AddField(
            model_name='eventoplano',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_plano_trabalho', to='viagens_planos.programasolicitante'),
        ),
        migrations.AddConstraint(
            model_name='efetivoevento',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_efetivoevento_origem'),
        ),
        migrations.AddConstraint(
            model_name='efetivoevento',
            constraint=models.UniqueConstraint(fields=('evento', 'unidade', 'cargo'), name='viagens_efetivo_evento_unidade_cargo_unique'),
        ),
        migrations.AddConstraint(
            model_name='planodestino',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_planodestino_origem'),
        ),
        migrations.AddConstraint(
            model_name='planodestino',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', True)), fields=('plano', 'ordem'), name='plano_destino_rascunho_ordem_unique'),
        ),
        migrations.AddConstraint(
            model_name='planodestino',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('evento', 'ordem'), name='plano_destino_evento_ordem_unique'),
        ),
        migrations.AddConstraint(
            model_name='efetivoplano',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_efetivoplano_origem'),
        ),
        migrations.AddConstraint(
            model_name='efetivoplano',
            constraint=models.UniqueConstraint(fields=('plano', 'unidade', 'cargo'), name='viagens_efetivo_plano_unidade_cargo_unique'),
        ),
        migrations.AddConstraint(
            model_name='presetatividadesplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_presetatividadesplanotrabalho_origem'),
        ),
        migrations.AddConstraint(
            model_name='presetatividadesplanotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('is_padrao', True)), fields=('is_padrao',), name='viagens_preset_padrao_unico'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_planotrabalho_origem'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('numero__isnull', False)), fields=('ano', 'numero'), name='viagens_plano_trabalho_ano_numero_unique'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('data_evento_fim__gte', models.F('data_evento_inicio'))), name='plano_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_valor_unitario__gte', 0)), name='plano_diaria_unitaria_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_valor_total__gte', 0)), name='plano_diaria_total_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_combinada_valor_unitario__gte', 0)), name='plano_diaria_comb_unitaria_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_combinada_valor_total__gte', 0)), name='plano_diaria_comb_total_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.UniqueConstraint(condition=models.Q(('legado_pk__isnull', False)), fields=('legado_origem', 'legado_pk'), name='f6_eventoplano_origem'),
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.CheckConstraint(condition=models.Q(('data_evento_fim__gte', models.F('data_evento_inicio'))), name='evento_plano_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_valor_unitario__gte', 0)), name='evento_plano_diaria_unitaria_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.CheckConstraint(condition=models.Q(('diarias_valor_total__gte', 0)), name='evento_plano_diaria_total_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.UniqueConstraint(fields=('plano', 'ordem'), name='evento_plano_ordem_unique'),
        ),
    ]
