# Generated by Django 6.1.1 on 2026-09-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_planos", "0003_catalogos_iniciais"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoTrabalhoNumeroLacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("numero", models.PositiveIntegerField()),
                ("liberado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Número de Plano de Trabalho liberado",
                "verbose_name_plural": "Números de Plano de Trabalho liberados",
                "ordering": ["ano", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ano", "numero"), name="plano_lacuna_ano_numero_unique"
                    )
                ],
            },
        ),
    ]
