# Generated by Django 6.1.1 on 2026-09-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_planos", "0005_horario_ate_com_acento"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "realizado",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Realizado"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="viagens_planos.atividadeplanotrabalho",
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="viagens_planos.planotrabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de atividade do plano",
                "verbose_name_plural": "Resultados das atividades do plano",
                "ordering": ["atividade__nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plano", "atividade"),
                        name="plano_resultado_atividade_unico",
                    )
                ],
            },
        ),
    ]
