# Generated by Django 6.1.1 on 2026-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_planos", "0006_resultados_das_atividades"),
    ]

    operations = [
        migrations.AddField(
            model_name="planotrabalho",
            name="data_documento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do documento"
            ),
        ),
    ]
