# Generated by Django 6.1.1 on 2026-09-27 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_cadastros", "0008_assinante_substituto"),
        ("viagens_planos", "0007_data_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="planotrabalho",
            name="assinante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="viagens_cadastros.servidor",
                verbose_name="Assinante deste plano",
            ),
        ),
    ]
