# Generated by Django 6.1.1 on 2026-09-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viagens_planos", "0008_assinante_substituto"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="efetivoevento",
            name="viagens_efetivo_evento_unidade_cargo_unique",
        ),
        migrations.RemoveConstraint(
            model_name="efetivoplano",
            name="viagens_efetivo_plano_unidade_cargo_unique",
        ),
    ]
